naureus.sk,"HTTPSConnectionPool(host='www.naureus.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.naureus.sk', port=443): Read timed out. (read timeout=2)"
nb.rs,"HTTPSConnectionPool(host='nb.rs', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.nb.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7496742dc0>, 'Connection to www.nb.rs timed out. (connect timeout=2)'))"
ncc.gov.ng,"HTTPSConnectionPool(host='ncc.gov.ng', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ncc.gov.ng', port=443): Read timed out. (read timeout=2)"
near-place.com,"HTTPSConnectionPool(host='near-place.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='near-place.com', port=80): Read timed out. (read timeout=2)"
neliti.com,"HTTPSConnectionPool(host='neliti.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.neliti.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
neopod.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='neopod.ru', port=80): Read timed out. (read timeout=2)"
neowing.co.jp,"HTTPSConnectionPool(host='neowing.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74973532b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='neowing.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7494c27fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nestia.com,"HTTPSConnectionPool(host='www.nestia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.nestia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))"
net.ee,"HTTPSConnectionPool(host='net.ee', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74937ba6a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='net.ee', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7494a37700>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
neturuguay.com,"HTTPSConnectionPool(host='neturuguay.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='neturuguay.com', port=443): Read timed out. (read timeout=2)"
netwerkgalerij.be,"HTTPSConnectionPool(host='netwerkgalerij.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7496558340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='netwerkgalerij.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492f5fa60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
neu.edu.tr,"HTTPSConnectionPool(host='neu.edu.tr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='neu.edu.tr', port=443): Read timed out. (read timeout=2)"
newellwind.com,"HTTPSConnectionPool(host='newellwind.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7492af9430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='newellwind.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492428d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
newpages.com.my,"HTTPSConnectionPool(host='www.newpages.com.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.newpages.com.my', port=443): Read timed out. (read timeout=2)"
news-italia-mondo.it,"HTTPSConnectionPool(host='news-italia-mondo.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='news-italia-mondo.it', port=80): Read timed out. (read timeout=2)"
newsformy.com,"HTTPSConnectionPool(host='newsformy.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='newsformy.com', port=443): Read timed out. (read timeout=2)"
newsincyprus.com,"HTTPSConnectionPool(host='newsincyprus.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1129)')))","HTTPConnectionPool(host='newsincyprus.com', port=80): Read timed out. (read timeout=2)"
newswire.ca,"HTTPSConnectionPool(host='newswire.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))","HTTPSConnectionPool(host='newswire.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))"
nguoiduatin.vn,"HTTPSConnectionPool(host='nguoiduatin.vn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f74968b3370>, 'Connection to nguoiduatin.vn timed out. (connect timeout=2)'))","HTTPConnectionPool(host='nguoiduatin.vn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f749268ddf0>, 'Connection to nguoiduatin.vn timed out. (connect timeout=2)'))"
nhk.or.jp,"HTTPSConnectionPool(host='nhk.or.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74966447c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nhk.or.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f749053b1c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ni.rs,"HTTPSConnectionPool(host='ni.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7499fdf2b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ni.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748f765f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nichepoliambulatorio.it,"HTTPSConnectionPool(host='nichepoliambulatorio.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='nichepoliambulatorio.it', port=80): Read timed out. (read timeout=2)"
nii.ac.jp,"HTTPSConnectionPool(host='nii.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7496802c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nii.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7494c14880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
niigata.lg.jp,"HTTPSConnectionPool(host='niigata.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74975a4ee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='niigata.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7496633fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nikkei.co.jp,"HTTPSConnectionPool(host='nikkei.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74945d64c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nikkei.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7496282fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ninhthuan.gov.vn,"HTTPConnectionPool(host='www.ninhthuan.gov.vn', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.ninhthuan.gov.vn', port=80): Read timed out. (read timeout=2)"
nippon.com,"HTTPSConnectionPool(host='nippon.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7498cf8370>, 'Connection to nippon.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='nippon.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7497eadd90>, 'Connection to nippon.com timed out. (connect timeout=2)'))"
njuzz.ee,"HTTPSConnectionPool(host='njuzz.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7495e4ee80>, 'Connection to njuzz.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='njuzz.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7495a744c0>, 'Connection to njuzz.ee timed out. (connect timeout=2)'))"
nojima.co.jp,"HTTPSConnectionPool(host='nojima.co.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7498589610>, 'Connection to nojima.co.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='nojima.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7495a85190>, 'Connection to nojima.co.jp timed out. (connect timeout=2)'))"
nomos-elibrary.de,"HTTPSConnectionPool(host='www.nomos-elibrary.de', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.nomos-elibrary.de', port=443): Read timed out. (read timeout=2)"
nonstopshop.rs,"HTTPSConnectionPool(host='nonstopshop.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='nonstopshop.rs', port=443): Read timed out. (read timeout=2)"
nord.no,"HTTPSConnectionPool(host='nord.no', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'nord.no' doesn't match either of 'www.nord.no', 'media.nord.no', 'min.nord.no', 'spfe-b-1.ad.nord.no', 'spfe-b-2.ad.nord.no'"")))","HTTPSConnectionPool(host='www.nord.no', port=443): Read timed out. (read timeout=2)"
norddjurs.dk,"HTTPSConnectionPool(host='www.norddjurs.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.norddjurs.dk', port=443): Read timed out. (read timeout=2)"
norham.org,"HTTPSConnectionPool(host='norham.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='norham.org', port=80): Read timed out. (read timeout=2)"
notepad.lv,"HTTPSConnectionPool(host='notepad.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74947165b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='notepad.lv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492d42190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
novine.hr,"HTTPSConnectionPool(host='novine.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='novine.hr', port=443): Read timed out. (read timeout=2)"
novosti.hr,"HTTPSConnectionPool(host='novosti.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='novosti.hr', port=443): Read timed out. (read timeout=2)"
npru.ac.th,"HTTPSConnectionPool(host='npru.ac.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.npru.ac.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
npz.sk,"HTTPSConnectionPool(host='npz.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
nrsr.sk,"HTTPSConnectionPool(host='nrsr.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f749199e940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nrsr.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492f5f4c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ns.ac.rs,"HTTPSConnectionPool(host='ns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74903fa5e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492987220>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nsc.ru,"HTTPSConnectionPool(host='nsc.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f74912ac850>, 'Connection to nsc.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='nsc.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f749199ed00>, 'Connection to nsc.ru timed out. (connect timeout=2)'))"
nsk.hr,"HTTPSConnectionPool(host='nsk.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='nsk.hr', port=443): Read timed out. (read timeout=2)"
nso.go.th,"HTTPSConnectionPool(host='nso.go.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7494ee5280>, 'Connection to nso.go.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='nso.go.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f74978be820>, 'Connection to nso.go.th timed out. (connect timeout=2)'))"
nstru.ac.th,"HTTPSConnectionPool(host='nstru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f749297b3a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='nstru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748f9801c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
nta.go.jp,"HTTPSConnectionPool(host='nta.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74968c5970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nta.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7492987730>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nttdocomo.co.jp,"HTTPSConnectionPool(host='nttdocomo.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7497f324f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nttdocomo.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7496265070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ntua.gr,"HTTPSConnectionPool(host='ntua.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74974fd220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='ntua.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7494a75a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
nucleodoconhecimento.com.br,"HTTPSConnectionPool(host='nucleodoconhecimento.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='nucleodoconhecimento.com.br', port=443): Read timed out. (read timeout=2)"
number1.co.il,"HTTPSConnectionPool(host='number1.co.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='number1.co.il', port=80): Read timed out. (read timeout=2)"
nusalist.com,"HTTPSConnectionPool(host='nearbymalaysia.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='nearbymalaysia.com', port=443): Read timed out. (read timeout=2)"
nuv.cz,"HTTPSConnectionPool(host='nuv.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)')))","HTTPConnectionPool(host='www.nuv.cz', port=80): Read timed out. (read timeout=2)"
nwu.ac.za,"HTTPSConnectionPool(host='nwu.ac.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7496282580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nwu.ac.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7497b301c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nyf.hu,"HTTPSConnectionPool(host='nyf.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f748e6b2af0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='nyf.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74962f9fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
nyitvatartas24.hu,"HTTPSConnectionPool(host='nyitvatartas24.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.nyitvatartas24.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))"
nzlii.org,"HTTPSConnectionPool(host='nzlii.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='nzlii.org', port=80): Read timed out. (read timeout=2)"
oae.go.th,"HTTPSConnectionPool(host='oae.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7491731f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='oae.go.th', port=80): Read timed out. (read timeout=2)"
oamk.fi,"HTTPSConnectionPool(host='www.oamk.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.oamk.fi', port=443): Read timed out. (read timeout=2)"
oas.org,"HTTPConnectionPool(host='www.oas.org', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.oas.org', port=80): Read timed out. (read timeout=2)"
obraspublicas.gob.ec,"HTTPSConnectionPool(host='obraspublicas.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'obraspublicas.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
obz.hr,"HTTPSConnectionPool(host='obz.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7497778670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='obz.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7495f488e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
oca.com.uy,"HTTPSConnectionPool(host='oca.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f748e6609d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='oca.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7497189f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
