stou.ac.th,"HTTPSConnectionPool(host='stou.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f947482a310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='stou.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f947482abb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
stradini.lv,"HTTPSConnectionPool(host='stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
straitstimes.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
strathmore.edu,"HTTPSConnectionPool(host='strathmore.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='strathmore.edu', port=443): Read timed out. (read timeout=2)"
struktuurifondid.ee,"HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
struma.bg,"HTTPSConnectionPool(host='struma.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='struma.bg', port=443): Read timed out. (read timeout=2)"
studentski.hr,"HTTPSConnectionPool(host='studentski.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='studentski.hr', port=443): Read timed out. (read timeout=2)"
studio-aix.com,"HTTPSConnectionPool(host='studio-aix.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9471ae4d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='studio-aix.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94742dadc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
studiolegalebazzanbettin.it,"HTTPSConnectionPool(host='studiolegalebazzanbettin.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='studiolegalebazzanbettin.it', port=80): Read timed out. (read timeout=2)"
studyrankersonline.com,"HTTPSConnectionPool(host='studyrankersonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'studyrankersonline.com' doesn't match 'www.studyrankersonline.com'"")))","HTTPSConnectionPool(host='studyrankersonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'studyrankersonline.com' doesn't match 'www.studyrankersonline.com'"")))"
stylesatlife.com,"HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)"
suaramerdeka.com,"HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)"
submarino.com.br,"HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)"
sud.rs,"HTTPSConnectionPool(host='sud.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9471edafa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sud.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9470763280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sudrf.ru,"HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
sukasa.com,"HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)"
sukl.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
sun.ac.za,"HTTPSConnectionPool(host='sun.ac.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94730d6340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sun.ac.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946ff5ad90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
superdrug.com,"HTTPSConnectionPool(host='superdrug.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='superdrug.com', port=80): Read timed out. (read timeout=2)"
supermag.bg,"HTTPSConnectionPool(host='supermag.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.supermag.bg', port=443): Read timed out. (read timeout=2)"
superpages.com,"HTTPSConnectionPool(host='superpages.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9471b73460>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='superpages.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946f81e520>: Failed to establish a new connection: [Errno 111] Connection refused'))"
superprof.co,"HTTPSConnectionPool(host='superprof.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f94724f5f10>, 'Connection to superprof.co timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.superprof.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f946dc98d00>, 'Connection to www.superprof.co timed out. (connect timeout=2)'))"
superprof.com.ar,"HTTPSConnectionPool(host='superprof.com.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f946ee08ca0>, 'Connection to superprof.com.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='superprof.com.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9472d8d130>, 'Connection to superprof.com.ar timed out. (connect timeout=2)'))"
superprof.com.br,"HTTPSConnectionPool(host='superprof.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f94726f7f70>, 'Connection to superprof.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='superprof.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f94744325b0>, 'Connection to superprof.com.br timed out. (connect timeout=2)'))"
surabaya.go.id,"HTTPSConnectionPool(host='surabaya.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))","HTTPSConnectionPool(host='surabaya.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))"
suruga-ya.jp,"HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))","HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))"
suslusozluk.com,"HTTPSConnectionPool(host='www.suslusozluk.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.suslusozluk.com', port=443): Read timed out. (read timeout=2)"
sut.ac.th,"HTTPSConnectionPool(host='sut.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946dbdf760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sut.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9474322640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
svejo.net,"HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)"
svu.edu.eg,"HTTPSConnectionPool(host='svu.edu.eg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946f5d1250>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='svu.edu.eg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946c7ef580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
svutennis.nl,"HTTPSConnectionPool(host='svutennis.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946e3ddf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='svutennis.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946c70dd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
swiat-zdrowia.pl,"HTTPSConnectionPool(host='swiat-zdrowia.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'swiat-zdrowia.pl' doesn't match either of '*.neuca.pl', 'neuca.pl'"")))","HTTPSConnectionPool(host='www.swiat-zdrowia.pl', port=443): Read timed out. (read timeout=2)"
swissinfo.ch,"HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
swu.bg,"HTTPSConnectionPool(host='swu.bg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946c7efac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='swu.bg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946b90f9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sydanmerkki.fi,"HTTPSConnectionPool(host='www.sydanmerkki.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sydanmerkki.fi', port=443): Read timed out. (read timeout=2)"
sydsvenskan.se,"HTTPSConnectionPool(host='www.sydsvenskan.se', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sydsvenskan.se', port=443): Read timed out. (read timeout=2)"
szu.sk,"HTTPSConnectionPool(host='szu.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946d1a32b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='szu.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946b5d65e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
t24.tn,"HTTPSConnectionPool(host='t24.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946fd71580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='t24.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946b4e5640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
taalwerkplaatsdrenthe.nl,"HTTPSConnectionPool(host='taalwerkplaatsdrenthe.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946d9703a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='taalwerkplaatsdrenthe.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9474ab4f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
tabirai.net,"HTTPSConnectionPool(host='tabirai.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946fbb7a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='tabirai.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9473ea5ac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
tablondeanuncios.com,Exceeded 30 redirects.,Exceeded 30 redirects.
tainhac365.org,"HTTPSConnectionPool(host='tainhac365.org', port=443): Read timed out.","HTTPSConnectionPool(host='tainhac365.org', port=443): Read timed out."
tallinnlv.ee,"HTTPSConnectionPool(host='tallinnlv.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9472745940>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tallinnlv.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f946f0d2820>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))"
tamano.ma,"HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
tamm.abudhabi,"HTTPSConnectionPool(host='www.tamm.abudhabi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tamm.abudhabi', port=80): Read timed out. (read timeout=2)"
target.com.au,"HTTPSConnectionPool(host='www.target.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.target.com.au', port=443): Read timed out. (read timeout=2)"
tayara.tn,"HTTPSConnectionPool(host='www.tayara.tn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tayara.tn', port=443): Read timed out. (read timeout=2)"
tcd.ie,"HTTPSConnectionPool(host='tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))"
tdgtest.it,"HTTPSConnectionPool(host='tdgtest.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tdgtest.it', port=80): Read timed out. (read timeout=2)"
teachfornigeria.org,"HTTPSConnectionPool(host='teachfornigeria.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='teachfornigeria.org', port=80): Read timed out. (read timeout=2)"
techcare.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
techmoran.com,"HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)"
technopro-online.com,"HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)"
techtunes.co,"HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)"
tecnacional.edu.ni,"HTTPSConnectionPool(host='tecnacional.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94749691c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='tecnacional.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9472e25d60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
tee.gr,"HTTPSConnectionPool(host='tee.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9469135be0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='tee.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946d970460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
teeitse.com,"HTTPSConnectionPool(host='teeitse.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='teeitse.com', port=443): Read timed out. (read timeout=2)"
teiath.gr,"HTTPSConnectionPool(host='teiath.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9473aa53a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='teiath.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f946d3a2610>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
teiemt.gr,"HTTPSConnectionPool(host='teiemt.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9472c14520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='teiemt.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94726bc820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
teiep.gr,"HTTPSConnectionPool(host='teiep.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f947252f490>, 'Connection to teiep.gr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='teiep.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f946c87a0d0>, 'Connection to teiep.gr timed out. (connect timeout=2)'))"
teimes.gr,"HTTPSConnectionPool(host='teimes.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9472ef3310>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='teimes.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f946c424580>, 'Connection to teimes.gr timed out. (connect timeout=2)'))"
teismai.lt,"HTTPSConnectionPool(host='teismai.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9473171d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='teismai.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9473e04460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
teithe.gr,"HTTPSConnectionPool(host='teithe.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9472fc4f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='teithe.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94742ccac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
teiwest.gr,"HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)')))","HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)')))"
telcel.com,"HTTPSConnectionPool(host='telcel.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))","HTTPConnectionPool(host='telcel.com', port=80): Read timed out. (read timeout=2)"
telecomunicaciones.gob.ec,"HTTPSConnectionPool(host='telecomunicaciones.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'telecomunicaciones.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
telefonai.eu,"HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)"
telefono-societa.it,"HTTPSConnectionPool(host='telefono-societa.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f946a322b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.telefono-societa.it', port=80): Read timed out. (read timeout=2)"
telepolis.pl,"HTTPSConnectionPool(host='www.telepolis.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.telepolis.pl', port=443): Read timed out. (read timeout=2)"
telhai.ac.il,"HTTPSConnectionPool(host='telhai.ac.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f94744325e0>, 'Connection to telhai.ac.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='telhai.ac.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9468f64eb0>, 'Connection to telhai.ac.il timed out. (connect timeout=2)'))"
