construmart.cl,"HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))","HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))"
consultoriaorigenydestino.com,"HTTPSConnectionPool(host='consultoriaorigenydestino.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='consultoriaorigenydestino.com', port=80): Read timed out. (read timeout=2)"
contdict.ru,"HTTPSConnectionPool(host='contdict.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991e294460>, 'Connection to contdict.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='contdict.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991ecf0550>, 'Connection to contdict.ru timed out. (connect timeout=2)'))"
contratos.gov.co,"HTTPSConnectionPool(host='contratos.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991e4ddee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='contratos.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991e328b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
controlsanitario.gob.ec,"HTTPSConnectionPool(host='controlsanitario.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'controlsanitario.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
coolicias.ao,"HTTPSConnectionPool(host='coolicias.ao', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='coolicias.ao', port=443): Read timed out. (read timeout=2)"
coomeva.com.co,"HTTPSConnectionPool(host='coomeva.com.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991beb4ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='coomeva.com.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991dab46d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cope.es,"HTTPSConnectionPool(host='cope.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cope.es', port=443): Read timed out."
copts-united.com,"HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)"
cordial.fr,"HTTPSConnectionPool(host='cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cordobavende.com,"HTTPSConnectionPool(host='www.cordobavende.com', port=443): Read timed out.","HTTPSConnectionPool(host='www.cordobavende.com', port=443): Read timed out. (read timeout=2)"
correo.com.uy,"HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
correodelorinoco.gob.ve,"HTTPSConnectionPool(host='correodelorinoco.gob.ve', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='www.correodelorinoco.gob.ve', port=80): Read timed out. (read timeout=2)"
cortera.com,"HTTPSConnectionPool(host='cortera.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991c59ba00>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='cortera.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991b1bc9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
cosicomodo.it,"HTTPSConnectionPool(host='cosicomodo.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991b15ceb0>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cosicomodo.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991b1abe20>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))"
cosmodata.gr,"HTTPSConnectionPool(host='cosmodata.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cosmodata.gr', port=443): Read timed out. (read timeout=2)"
cosmote.gr,Exceeded 30 redirects.,"HTTPSConnectionPool(host='www.cosmote.gr', port=443): Max retries exceeded with url: /fixed/not-found (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991bee8730>, 'Connection to www.cosmote.gr timed out. (connect timeout=2)'))"
costruzioniab.it,"HTTPSConnectionPool(host='costruzioniab.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='costruzioniab.it', port=80): Read timed out. (read timeout=2)"
cotidianul.ro,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
couriermail.com.au,"HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)"
covidmotion.net,"HTTPSConnectionPool(host='covidmotion.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991d23f460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='covidmotion.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99192f92e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
covybrat.sk,"HTTPSConnectionPool(host='www.covybrat.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.covybrat.sk', port=443): Read timed out. (read timeout=2)"
cpfreshmartshop.com,"HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)"
cppceo.com,"HTTPSConnectionPool(host='cppceo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991c71ddc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cppceo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991d1ea8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cput.ac.za,"HTTPSConnectionPool(host='cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
crececontigo.gob.cl,"HTTPSConnectionPool(host='crececontigo.gob.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9919328ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='crececontigo.gob.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991992eeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
crru.ac.th,"HTTPSConnectionPool(host='crru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991d861d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='crru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991a931ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
csfd.cz,"HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)"
csic.es,"HTTPSConnectionPool(host='csic.es', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991e7cf730>, 'Connection to csic.es timed out. (connect timeout=2)'))","HTTPConnectionPool(host='csic.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991e3283d0>, 'Connection to csic.es timed out. (connect timeout=2)'))"
csioz.gov.pl,"HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
csj.gob.sv,"HTTPSConnectionPool(host='csj.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99179e1d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='csj.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991bb6ea00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cssz.cz,"HTTPSConnectionPool(host='cssz.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9917bb4d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cssz.cz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991cc34730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
csun.edu,"HTTPSConnectionPool(host='csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cu.rs,"HTTPSConnectionPool(host='cu.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991bb6e7f0>, 'Connection to cu.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cu.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f99178ccf70>, 'Connection to cu.rs timed out. (connect timeout=2)'))"
cubadebate.cu,"HTTPSConnectionPool(host='cubadebate.cu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991f633a60>, 'Connection to cubadebate.cu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.cubadebate.cu', port=80): Read timed out. (read timeout=2)"
cultura.cr,"HTTPSConnectionPool(host='cultura.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991d0f7130>, 'Connection to cultura.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cultura.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991cadfd90>, 'Connection to cultura.cr timed out. (connect timeout=2)'))"
cultura.gob.ar,"HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)"
culturamix.com,"HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)"
culturaypatrimonio.gob.ec,"HTTPSConnectionPool(host='culturaypatrimonio.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'culturaypatrimonio.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cumhuriyet.edu.tr,"HTTPSConnectionPool(host='cumhuriyet.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991ca651c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cumhuriyet.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991c4c4ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
customs.gov.vn,"HTTPSConnectionPool(host='customs.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.customs.gov.vn', port=443): Read timed out. (read timeout=2)"
cut.ac.cy,"HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cvtisr.sk,"HTTPSConnectionPool(host='cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cvut.cz,"HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
czechdesign.cz,"HTTPSConnectionPool(host='czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
daba.lv,"HTTPSConnectionPool(host='daba.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99156dde80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='daba.lv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991bb2a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dados.gov.br,"HTTPSConnectionPool(host='dados.gov.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dados.gov.br', port=443): Read timed out. (read timeout=2)"
dagsavisen.no,"HTTPSConnectionPool(host='www.dagsavisen.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dagsavisen.no', port=443): Read timed out. (read timeout=2)"
dailygizmo.tv,"HTTPSConnectionPool(host='www.dailygizmo.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dailygizmo.tv', port=443): Read timed out. (read timeout=2)"
dailyvanity.sg,"HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)"
daiwahouse.co.jp,"HTTPSConnectionPool(host='daiwahouse.co.jp', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='daiwahouse.co.jp', port=80): Read timed out. (read timeout=2)"
dakinspectiedrone.nl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
daleli.sa,"HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
damernasvarld.se,"HTTPSConnectionPool(host='www.damernasvarld.se', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.damernasvarld.se', port=443): Read timed out. (read timeout=2)"
dane.gov.co,"HTTPSConnectionPool(host='dane.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991e090610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dane.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991e5a5af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
daradaily.com,"HTTPSConnectionPool(host='daradaily.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.daradaily.com', port=443): Read timed out. (read timeout=2)"
darikradio.bg,"HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
data.bg,"HTTPSConnectionPool(host='data.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='data.bg', port=80): Read timed out. (read timeout=2)"
data.gov.my,"HTTPSConnectionPool(host='data.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991c1e8610>, 'Connection to data.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='data.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9919982be0>, 'Connection to data.gov.my timed out. (connect timeout=2)'))"
datasus.gov.br,"HTTPSConnectionPool(host='datasus.gov.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991cb88850>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='datasus.gov.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991587c4f0>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))"
dca.gob.gt,"HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)"
dcs.vn,"HTTPSConnectionPool(host='dcs.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f991be6e4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dcs.vn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9915678220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
deacademic.com,"HTTPSConnectionPool(host='deacademic.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='deacademic.com', port=80): Read timed out. (read timeout=2)"
dealbunny.de,"HTTPSConnectionPool(host='www.dealbunny.de', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dealbunny.de', port=443): Read timed out. (read timeout=2)"
deals365.gr,"HTTPSConnectionPool(host='deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
decisoesesolucoes.com,"HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)"
decklinsdomain.org,"HTTPConnectionPool(host='www.decklinsdomain.org', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.decklinsdomain.org', port=80): Read timed out. (read timeout=2)"
defense.gouv.fr,"HTTPSConnectionPool(host='defense.gouv.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9916492490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='defense.gouv.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9917b77bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
defensoria.gob.bo,"HTTPSConnectionPool(host='defensoria.gob.bo', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9916eede80>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gob.bo', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f99209eb0a0>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))"
defensoria.gob.sv,"HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)"
defensoria.gov.co,"HTTPSConnectionPool(host='defensoria.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f991e451d00>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f991be472e0>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))"
deguate.com.gt,"HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)"
delo-vcusa.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
denzeltje.nl,"HTTPSConnectionPool(host='denzeltje.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99174c6d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='denzeltje.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f991ca65dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dep.com.vn,"HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)"
depo.lv,"HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
desant.net,"HTTPSConnectionPool(host='desant.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.desant.net', port=80): Read timed out. (read timeout=2)"
