construmart.cl,"HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))","HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))"
contdict.ru,"HTTPSConnectionPool(host='contdict.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b5fcf3a0>, 'Connection to contdict.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='contdict.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65b6bcf3a0>, 'Connection to contdict.ru timed out. (connect timeout=2)'))"
contratos.gov.co,"HTTPSConnectionPool(host='contratos.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b6bcf7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='contratos.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b604d5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
controlsanitario.gob.ec,"HTTPSConnectionPool(host='controlsanitario.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'controlsanitario.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
coomeva.com.co,"HTTPSConnectionPool(host='coomeva.com.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b3c37c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='coomeva.com.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b5c3adc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
copts-united.com,"HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)"
cordial.fr,"HTTPSConnectionPool(host='cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
correo.com.uy,"HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cortera.com,"HTTPSConnectionPool(host='cortera.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b5107c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='cortera.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b5306c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
cosicomodo.it,"HTTPSConnectionPool(host='cosicomodo.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b2729e50>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cosicomodo.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65b6bcfb20>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))"
cosmote.gr,Exceeded 30 redirects.,Exceeded 30 redirects.
costruzioniab.it,"HTTPSConnectionPool(host='costruzioniab.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='costruzioniab.it', port=80): Read timed out. (read timeout=2)"
cotidianul.ro,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
couriermail.com.au,"HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)"
courrier-picard.fr,"HTTPSConnectionPool(host='courrier-picard.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.courrier-picard.fr', port=443): Read timed out. (read timeout=2)"
covidmotion.net,"HTTPSConnectionPool(host='covidmotion.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b3e03d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='covidmotion.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b0da2a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
cpfreshmartshop.com,"HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)"
cppceo.com,"HTTPSConnectionPool(host='cppceo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b4019850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cppceo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b21923a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cput.ac.za,"HTTPSConnectionPool(host='cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
crececontigo.gob.cl,"HTTPSConnectionPool(host='crececontigo.gob.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b0ad2b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='crececontigo.gob.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b0da2550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
crru.ac.th,"HTTPSConnectionPool(host='crru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b4d86610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='crru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b72ec190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
csfd.cz,"HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)"
csic.es,"HTTPSConnectionPool(host='csic.es', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65af5f74f0>, 'Connection to csic.es timed out. (connect timeout=2)'))","HTTPConnectionPool(host='csic.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65b5996af0>, 'Connection to csic.es timed out. (connect timeout=2)'))"
csioz.gov.pl,"HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
csj.gob.sv,"HTTPSConnectionPool(host='csj.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65af5f75e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='csj.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b11970d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cssz.cz,"HTTPSConnectionPool(host='cssz.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b0cf9490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cssz.cz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b4ba52b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
csun.edu,"HTTPSConnectionPool(host='csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cu.rs,"HTTPSConnectionPool(host='cu.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b59d3e80>, 'Connection to cu.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cu.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65afaa9550>, 'Connection to cu.rs timed out. (connect timeout=2)'))"
cucinare.tv,"HTTPSConnectionPool(host='www.cucinare.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cucinare.tv', port=443): Read timed out. (read timeout=2)"
cugetliber.ro,"HTTPSConnectionPool(host='cugetliber.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cugetliber.ro', port=443): Read timed out. (read timeout=2)"
cultura.cr,"HTTPSConnectionPool(host='cultura.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b5ed2e80>, 'Connection to cultura.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cultura.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65b59705e0>, 'Connection to cultura.cr timed out. (connect timeout=2)'))"
cultura.gob.ar,"HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)"
cultura.gob.mx,"HTTPSConnectionPool(host='www.gob.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gob.mx', port=443): Read timed out. (read timeout=2)"
culturamix.com,"HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)"
culturaypatrimonio.gob.ec,"HTTPSConnectionPool(host='culturaypatrimonio.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'culturaypatrimonio.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cumhuriyet.edu.tr,"HTTPSConnectionPool(host='cumhuriyet.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65ae744a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cumhuriyet.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b415df40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
customs.gov.vn,"HTTPSConnectionPool(host='customs.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.customs.gov.vn', port=443): Read timed out. (read timeout=2)"
cut.ac.cy,"HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cvtisr.sk,"HTTPSConnectionPool(host='cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cvut.cz,"HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cyclowiki.org,"HTTPConnectionPool(host='cyclowiki.org', port=80): Read timed out.","HTTPConnectionPool(host='cyclowiki.org', port=80): Read timed out."
czechdesign.cz,"HTTPSConnectionPool(host='czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
daba.lv,"HTTPSConnectionPool(host='daba.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b5cac820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='daba.lv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65ade569a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dagospia.com,"HTTPSConnectionPool(host='dagospia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.dagospia.com', port=443): Read timed out. (read timeout=2)"
dailygizmo.tv,"HTTPSConnectionPool(host='www.dailygizmo.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dailygizmo.tv', port=443): Read timed out. (read timeout=2)"
dailyvanity.sg,"HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)"
daiwahouse.co.jp,"HTTPSConnectionPool(host='daiwahouse.co.jp', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='daiwahouse.co.jp', port=80): Read timed out. (read timeout=2)"
dakinspectiedrone.nl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
daleli.sa,"HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
dalmacijanews.hr,"HTTPSConnectionPool(host='dalmacijanews.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dalmacijanews.hr', port=443): Read timed out. (read timeout=2)"
dane.gov.co,"HTTPSConnectionPool(host='dane.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65ad1bb190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dane.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65ad79b520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dar-alifta.org,"HTTPSConnectionPool(host='dar-alifta.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dar-alifta.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b2a8c8e0>, 'Connection to www.dar-alifta.org timed out. (connect timeout=2)'))"
darikradio.bg,"HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
data.bg,"HTTPSConnectionPool(host='data.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='data.bg', port=80): Read timed out. (read timeout=2)"
data.gov.il,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
data.gov.my,"HTTPSConnectionPool(host='data.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b5ff34c0>, 'Connection to data.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='data.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65b5060e50>, 'Connection to data.gov.my timed out. (connect timeout=2)'))"
datasus.gov.br,"HTTPSConnectionPool(host='datasus.gov.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b4ff6190>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='datasus.gov.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65ad10e580>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))"
daugavpils.lv,"HTTPSConnectionPool(host='www.daugavpils.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.daugavpils.lv', port=443): Read timed out. (read timeout=2)"
dca.gob.gt,"HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)"
dcs.vn,"HTTPSConnectionPool(host='dcs.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b0b6bb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dcs.vn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b34eb8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
deacademic.com,"HTTPSConnectionPool(host='deacademic.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='deacademic.com', port=443): Read timed out. (read timeout=2)"
deals365.gr,"HTTPSConnectionPool(host='deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
decisoesesolucoes.com,"HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)"
defense.gouv.fr,"HTTPSConnectionPool(host='defense.gouv.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65b4f91970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='defense.gouv.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65ad1268e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
defensoria.gob.bo,"HTTPSConnectionPool(host='defensoria.gob.bo', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65b6010ac0>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gob.bo', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65ad2e04f0>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))"
defensoria.gob.sv,"HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)"
defensoria.gov.co,"HTTPSConnectionPool(host='defensoria.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65ad155640>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f65aebcf9a0>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))"
deguate.com.gt,"HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)"
delo-vcusa.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
denzeltje.nl,"HTTPSConnectionPool(host='denzeltje.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f65acb6d5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='denzeltje.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65b4121dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dep.com.vn,"HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)"
depo.lv,"HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
