construmart.cl,"HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))","HTTPSConnectionPool(host='construmart.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'construmart.cl' doesn't match '*.construmart.cl'"")))"
contdict.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
contratos.gov.co,"HTTPSConnectionPool(host='contratos.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9033cc3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='contratos.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90341c4f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
controlsanitario.gob.ec,"HTTPSConnectionPool(host='controlsanitario.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'controlsanitario.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
coomeva.com.co,"HTTPSConnectionPool(host='coomeva.com.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f903252da30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='coomeva.com.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f903392f7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
copts-united.com,"HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='copts-united.com', port=443): Read timed out. (read timeout=2)"
copyan.com,"HTTPSConnectionPool(host='copyan.com', port=443): Read timed out. (read timeout=2)",No host specified.
cordial.fr,"HTTPSConnectionPool(host='cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cordial.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
correo.com.uy,"HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='correo.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
correodelorinoco.gob.ve,"HTTPSConnectionPool(host='correodelorinoco.gob.ve', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='www.correodelorinoco.gob.ve', port=80): Read timed out. (read timeout=2)"
cortera.com,"HTTPSConnectionPool(host='cortera.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90305a4640>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='cortera.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9031137430>: Failed to establish a new connection: [Errno 111] Connection refused'))"
cosicomodo.it,"HTTPSConnectionPool(host='cosicomodo.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9031db99a0>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cosicomodo.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90310007f0>, 'Connection to cosicomodo.it timed out. (connect timeout=2)'))"
cosmote.gr,Exceeded 30 redirects.,Exceeded 30 redirects.
cotidianul.ro,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
couriermail.com.au,"HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.couriermail.com.au', port=443): Read timed out. (read timeout=2)"
covidmotion.net,"HTTPSConnectionPool(host='covidmotion.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f903316a5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='covidmotion.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f903281d040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
covybrat.sk,"HTTPSConnectionPool(host='www.covybrat.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.covybrat.sk', port=443): Read timed out. (read timeout=2)"
cpfreshmartshop.com,"HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cpfreshmartshop.com', port=443): Read timed out. (read timeout=2)"
cppceo.com,"HTTPSConnectionPool(host='cppceo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9032496280>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cppceo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f902f1bc8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cput.ac.za,"HTTPSConnectionPool(host='cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cput.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
creativebloq.com,"HTTPSConnectionPool(host='creativebloq.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9032496280>, 'Connection to creativebloq.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='creativebloq.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902ecf5040>, 'Connection to creativebloq.com timed out. (connect timeout=2)'))"
crececontigo.gob.cl,"HTTPSConnectionPool(host='crececontigo.gob.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9030c9aaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='crececontigo.gob.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9030ff6c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
crru.ac.th,"HTTPSConnectionPool(host='crru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9033061b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='crru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f903431e070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
csfd.cz,"HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.csfd.cz', port=443): Read timed out. (read timeout=2)"
csic.es,"HTTPSConnectionPool(host='csic.es', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f902dab72b0>, 'Connection to csic.es timed out. (connect timeout=2)'))","HTTPConnectionPool(host='csic.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902eeb51c0>, 'Connection to csic.es timed out. (connect timeout=2)'))"
csioz.gov.pl,"HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='csioz.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
csj.gob.sv,"HTTPSConnectionPool(host='csj.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f902dab7c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='csj.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9034582fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cssz.cz,"HTTPSConnectionPool(host='cssz.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f902d928ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cssz.cz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9034e4c520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
csun.edu,"HTTPSConnectionPool(host='csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.csun.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cu.rs,"HTTPSConnectionPool(host='cu.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9033482d60>, 'Connection to cu.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cu.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902cf5ec10>, 'Connection to cu.rs timed out. (connect timeout=2)'))"
cucinare.tv,"HTTPSConnectionPool(host='www.cucinare.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cucinare.tv', port=443): Read timed out. (read timeout=2)"
cugetliber.ro,"HTTPSConnectionPool(host='cugetliber.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cugetliber.ro', port=443): Read timed out. (read timeout=2)"
cultura.cr,"HTTPSConnectionPool(host='cultura.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9032c257c0>, 'Connection to cultura.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cultura.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902d4668b0>, 'Connection to cultura.cr timed out. (connect timeout=2)'))"
cultura.gob.ar,"HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cultura.gob.ar', port=443): Read timed out. (read timeout=2)"
culturamix.com,"HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='culturamix.com', port=443): Read timed out. (read timeout=2)"
culturaypatrimonio.gob.ec,"HTTPSConnectionPool(host='culturaypatrimonio.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'culturaypatrimonio.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cumhuriyet.edu.tr,"HTTPSConnectionPool(host='cumhuriyet.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9034c3f6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cumhuriyet.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f902c8da310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cunghocvui.com,"HTTPSConnectionPool(host='cunghocvui.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cunghocvui.com', port=443): Read timed out. (read timeout=2)"
customs.gov.vn,"HTTPSConnectionPool(host='customs.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.customs.gov.vn', port=443): Read timed out. (read timeout=2)"
cut.ac.cy,"HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cut.ac.cy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cvtisr.sk,"HTTPSConnectionPool(host='cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cvtisr.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
cvut.cz,"HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cvut.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cybersrilanka.com,"HTTPSConnectionPool(host='cybersrilanka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cybersrilanka.com', port=443): Read timed out. (read timeout=2)"
czechdesign.cz,"HTTPSConnectionPool(host='czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.czechdesign.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
daba.lv,"HTTPSConnectionPool(host='daba.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f902f2eb100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='daba.lv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f902b95af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dabasdati.lv,"HTTPSConnectionPool(host='dabasdati.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dabasdati.lv', port=443): Read timed out. (read timeout=2)"
dailygizmo.tv,"HTTPSConnectionPool(host='www.dailygizmo.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dailygizmo.tv', port=443): Read timed out. (read timeout=2)"
dailytelegraph.com.au,"HTTPSConnectionPool(host='www.dailytelegraph.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dailytelegraph.com.au', port=443): Read timed out. (read timeout=2)"
dailyvanity.sg,"HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dailyvanity.sg', port=443): Read timed out. (read timeout=2)"
daiwahouse.co.jp,"HTTPSConnectionPool(host='daiwahouse.co.jp', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='daiwahouse.co.jp', port=80): Read timed out. (read timeout=2)"
dakinspectiedrone.nl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
daleli.sa,"HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='daleli.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
dane.gov.co,"HTTPSConnectionPool(host='dane.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9031fb2130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dane.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f902b56fe50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
daradaily.com,"HTTPSConnectionPool(host='daradaily.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.daradaily.com', port=443): Read timed out. (read timeout=2)"
darikradio.bg,"HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='darikradio.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
data.bg,"HTTPSConnectionPool(host='data.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='data.bg', port=80): Read timed out. (read timeout=2)"
data.gov.il,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
data.gov.my,"HTTPSConnectionPool(host='data.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9031e7ee20>, 'Connection to data.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='data.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902b84baf0>, 'Connection to data.gov.my timed out. (connect timeout=2)'))"
datasus.gov.br,"HTTPSConnectionPool(host='datasus.gov.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90367baeb0>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='datasus.gov.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9034e4cd00>, 'Connection to datasus.gov.br timed out. (connect timeout=2)'))"
dca.gob.gt,"HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dca.gob.gt', port=443): Read timed out. (read timeout=2)"
dci.com.br,"HTTPSConnectionPool(host='www.dci.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.dci.com.br', port=443): Read timed out. (read timeout=2)"
dcs.vn,"HTTPSConnectionPool(host='dcs.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f902b605520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='dcs.vn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f903372a880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
deals365.gr,"HTTPSConnectionPool(host='deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.deals365.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
deavita.com,"HTTPSConnectionPool(host='deavita.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='deavita.com', port=443): Read timed out. (read timeout=2)"
decisoesesolucoes.com,"HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='decisoesesolucoes.com', port=443): Read timed out. (read timeout=2)"
defense.gouv.fr,"HTTPSConnectionPool(host='defense.gouv.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f902b5b1430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='defense.gouv.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f902b205ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
defensoria.gob.bo,"HTTPSConnectionPool(host='defensoria.gob.bo', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f902b4699a0>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gob.bo', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902b227190>, 'Connection to defensoria.gob.bo timed out. (connect timeout=2)'))"
defensoria.gob.sv,"HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='defensoria.gob.sv', port=443): Read timed out. (read timeout=2)"
defensoria.gov.co,"HTTPSConnectionPool(host='defensoria.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9031d297f0>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='defensoria.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f902f470a90>, 'Connection to defensoria.gov.co timed out. (connect timeout=2)'))"
deguate.com.gt,"HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.deguate.com.gt', port=443): Read timed out. (read timeout=2)"
delo-vcusa.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
denzeltje.nl,"HTTPSConnectionPool(host='denzeltje.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90333bbe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='denzeltje.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9032d78a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
dep.com.vn,"HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='dep.com.vn', port=443): Read timed out. (read timeout=2)"
depo.lv,"HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='depo.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
