geocities.jp,"HTTPSConnectionPool(host='geocities.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad9a87b4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='geocities.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad9a87bdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
geomedian.com,"HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gesetze-im-internet.de,"HTTPSConnectionPool(host='gesetze-im-internet.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad9810df10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesetze-im-internet.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad97a2c520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gestionderiesgos.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
gesundheitsinformation.de,"HTTPSConnectionPool(host='gesundheitsinformation.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad978dcdc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesundheitsinformation.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad9738dac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
get.bg,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
getnews.jp,"HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)"
gets.govt.nz,"HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)"
geva.co.il,"HTTPSConnectionPool(host='geva.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.geva.co.il', port=443): Read timed out. (read timeout=2)"
ghidulprimariilor.ro,"HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
giftly.com,"HTTPSConnectionPool(host='giftly.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'giftly.com' doesn't match either of 'shortener.secureserver.net', 'www.shortener.secureserver.net'"")))","HTTPConnectionPool(host='giftly.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad95613b50>, 'Connection to giftly.com timed out. (connect timeout=2)'))"
gifu.lg.jp,"HTTPSConnectionPool(host='gifu.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad9795e4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gifu.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad95657670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gigabaza.ru,"HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gismeteo.lt,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.lv,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.pl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ua,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
givatayim.muni.il,"HTTPSConnectionPool(host='givatayim.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad98039820>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='givatayim.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad94f8bd00>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))"
gizzmo.si,"HTTPSConnectionPool(host='gizzmo.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='gizzmo.si', port=443): Read timed out. (read timeout=2)"
glasistre.hr,"HTTPSConnectionPool(host='glasistre.hr', port=443): Read timed out.","HTTPConnectionPool(host='glasistre.hr', port=80): Read timed out."
glassumadije.rs,"HTTPSConnectionPool(host='www.glassumadije.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.glassumadije.rs', port=80): Read timed out. (read timeout=2)"
glints.com,"HTTPSConnectionPool(host='glints.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='glints.com', port=443): Read timed out. (read timeout=2)"
gme.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gnr.pt,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
gobiernodecanarias.org,"HTTPSConnectionPool(host='gobiernodecanarias.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad94ed2d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gobiernodecanarias.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad9288fca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
goerdetselv.dk,"HTTPSConnectionPool(host='goerdetselv.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='goerdetselv.dk', port=443): Read timed out. (read timeout=2)"
gogov.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
goias.gov.br,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
golos.com.ua,"HTTPSConnectionPool(host='golos.com.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad98de96d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.golos.com.ua', port=80): Read timed out. (read timeout=2)"
goodfood.com.au,"HTTPSConnectionPool(host='goodfood.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad97d3bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
goodiz.tv,"HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)"
goodsongs.com.ua,"HTTPSConnectionPool(host='goodsongs.com.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='goodsongs.com.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
googleusercontent.com,"HTTPSConnectionPool(host='googleusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad9000a8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad90b35670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gorzow.pl,"HTTPSConnectionPool(host='gorzow.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad935e9be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gorzow.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad8e908160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gotomanager.com,"HTTPSConnectionPool(host='gotomanager.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad93e967c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='gotomanager.com', port=80): Read timed out. (read timeout=2)"
gourmet.cl,"HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)"
gov.bc.ca,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gov.hu,"HTTPSConnectionPool(host='gov.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad9834c880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gov.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad8fec1430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
govextra.gov.il,"HTTPSConnectionPool(host='govextra.gov.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='govextra.gov.il', port=443): Read timed out. (read timeout=2)"
gpoint.co.jp,"HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))","HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))"
grad-zadar.hr,"HTTPSConnectionPool(host='grad-zadar.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad8f4b92b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grad-zadar.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad98913fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gramatnicaglobuss.lv,"HTTPSConnectionPool(host='gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)"
grancursosonline.com.br,"HTTPSConnectionPool(host='www.grancursosonline.com.br', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='grancursosonline.com.br', port=80): Read timed out. (read timeout=2)"
grazia.it,"HTTPSConnectionPool(host='grazia.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad8f3e9a30>, 'Connection to grazia.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='grazia.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad92ba6d90>, 'Connection to grazia.it timed out. (connect timeout=2)'))"
graziadaily.co.uk,"HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)"
grizly.cz,"HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)"
grizly.sk,"HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)"
gruene.at,"HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)"
grupolusofona.pt,"HTTPSConnectionPool(host='grupolusofona.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad95ed0070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grupolusofona.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad959ab7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gsb.gov.tr,"HTTPSConnectionPool(host='gsb.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad969210d0>, 'Connection to gsb.gov.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='gsb.gov.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad97ca6f10>, 'Connection to gsb.gov.tr timed out. (connect timeout=2)'))"
gsb.or.th,"HTTPSConnectionPool(host='gsb.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad956c2160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gsb.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad97045130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gtp.gr,"HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))","HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))"
guaranteepra.com,"HTTPSConnectionPool(host='guaranteepra.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad95686c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='guaranteepra.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad97f2ff40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
guiadelocio.com,"HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)"
guiagt.com,"HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)"
guiato.com.br,"HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gunadarma.ac.id,"HTTPSConnectionPool(host='gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
guru.ua,"HTTPSConnectionPool(host='guru.ua', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='guru.ua', port=80): Read timed out. (read timeout=2)"
guru99.com,"HTTPSConnectionPool(host='guru99.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad928bfa90>, 'Connection to guru99.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='guru99.com', port=80): Read timed out. (read timeout=2)"
gustissimo.it,"HTTPSConnectionPool(host='gustissimo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.gustissimo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
guzzle.co.za,"HTTPSConnectionPool(host='guzzle.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'guzzle.co.za' doesn't match 'www.guzzle.co.za'"")))","HTTPSConnectionPool(host='www.guzzle.co.za', port=443): Read timed out. (read timeout=2)"
gyogyszernelkul.com,"HTTPSConnectionPool(host='gyogyszernelkul.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad960d5bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gyogyszernelkul.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fad991dd2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gyorplusz.hu,"HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)"
ha.rs,"HTTPSConnectionPool(host='ha.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad90108ac0>, 'Connection to ha.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ha.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad95c531f0>, 'Connection to ha.rs timed out. (connect timeout=2)'))"
haapsalu.ee,"HTTPSConnectionPool(host='haapsalu.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'haapsalu.ee' doesn't match either of '*.kovtp.ee', 'kovtp.ee'"")))","HTTPSConnectionPool(host='www.haapsalu.ee', port=443): Read timed out. (read timeout=2)"
haifa.ac.il,"HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
hakolhayehudi.co.il,"HTTPSConnectionPool(host='www.hakolhayehudi.co.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='hakolhayehudi.co.il', port=80): Read timed out."
halodoc.com,"HTTPSConnectionPool(host='halodoc.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fad962be8e0>, 'Connection to halodoc.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='halodoc.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fad95a36c70>, 'Connection to halodoc.com timed out. (connect timeout=2)'))"
hamazo.tv,"HTTPSConnectionPool(host='hamazo.tv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.hamazo.tv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
