geocities.jp,"HTTPSConnectionPool(host='geocities.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9673744670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='geocities.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9673744f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
geomedian.com,"HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gesetze-im-internet.de,"HTTPSConnectionPool(host='gesetze-im-internet.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9672198eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesetze-im-internet.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9670cbfc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gestionderiesgos.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
gesundheitsinformation.de,"HTTPSConnectionPool(host='gesundheitsinformation.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9670b37c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesundheitsinformation.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96705e0220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
get.bg,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
getnews.jp,"HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)"
gets.govt.nz,"HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)"
geva.co.il,"HTTPSConnectionPool(host='geva.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.geva.co.il', port=443): Read timed out. (read timeout=2)"
ghidulprimariilor.ro,"HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
giancarlorizza.it,"HTTPSConnectionPool(host='giancarlorizza.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='giancarlorizza.it', port=80): Read timed out. (read timeout=2)"
gifu.lg.jp,"HTTPSConnectionPool(host='gifu.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966fec5fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gifu.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f966e215700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gigabaza.ru,"HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gismeteo.lt,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.lv,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.pl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ua,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
giuntialpunto.it,"HTTPSConnectionPool(host='giuntialpunto.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'giuntialpunto.it' doesn't match either of '*.giunti.it', 'giunti.it'"")))","HTTPSConnectionPool(host='www.giuntialpunto.it', port=443): Read timed out. (read timeout=2)"
givatayim.muni.il,"HTTPSConnectionPool(host='givatayim.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f966d204460>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='givatayim.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f966f43edf0>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))"
gizmodo.jp,"HTTPSConnectionPool(host='www.gizmodo.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gizmodo.jp', port=443): Read timed out. (read timeout=2)"
glasistre.hr,"HTTPSConnectionPool(host='glasistre.hr', port=443): Read timed out.","HTTPConnectionPool(host='glasistre.hr', port=80): Read timed out."
glassumadije.rs,"HTTPSConnectionPool(host='www.glassumadije.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.glassumadije.rs', port=80): Read timed out. (read timeout=2)"
gme.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gnr.pt,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
go4worldbusiness.com,"HTTPSConnectionPool(host='www.go4worldbusiness.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.go4worldbusiness.com', port=443): Read timed out. (read timeout=2)"
gobiernodecanarias.org,"HTTPSConnectionPool(host='gobiernodecanarias.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966a526a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gobiernodecanarias.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f966a5047f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
goerdetselv.dk,"HTTPSConnectionPool(host='goerdetselv.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='goerdetselv.dk', port=443): Read timed out. (read timeout=2)"
gogov.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
goias.gov.br,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
goldcoastbulletin.com.au,"HTTPSConnectionPool(host='www.goldcoastbulletin.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.goldcoastbulletin.com.au', port=443): Read timed out. (read timeout=2)"
golos.com.ua,"HTTPSConnectionPool(host='golos.com.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96709fc190>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.golos.com.ua', port=80): Read timed out. (read timeout=2)"
gomhuriaonline.com,"HTTPSConnectionPool(host='www.gomhuriaonline.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gomhuriaonline.com', port=443): Read timed out. (read timeout=2)"
gonews.it,"HTTPSConnectionPool(host='www.gonews.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gonews.it', port=443): Read timed out. (read timeout=2)"
goodfood.com.au,"HTTPSConnectionPool(host='goodfood.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96694afeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
goodiz.tv,"HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)"
goodkitchendesign.com,"HTTPSConnectionPool(host='goodkitchendesign.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='goodkitchendesign.com', port=443): Read timed out. (read timeout=2)"
goodsongs.com.ua,"HTTPSConnectionPool(host='goodsongs.com.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='goodsongs.com.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
googleusercontent.com,"HTTPSConnectionPool(host='googleusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9668134580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f966c19d550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gorzow.pl,"HTTPSConnectionPool(host='gorzow.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966e4e29d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gorzow.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9668932100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gotomanager.com,"HTTPSConnectionPool(host='gotomanager.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96710f1520>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='gotomanager.com', port=80): Read timed out. (read timeout=2)"
gourmet.cl,"HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)"
gov.bc.ca,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gov.hu,"HTTPSConnectionPool(host='gov.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f967126c970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gov.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9669398130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
govextra.gov.il,"HTTPSConnectionPool(host='govextra.gov.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='govextra.gov.il', port=443): Read timed out. (read timeout=2)"
gpoint.co.jp,"HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))","HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))"
gqjapan.jp,"HTTPSConnectionPool(host='www.gqjapan.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gqjapan.jp', port=443): Read timed out. (read timeout=2)"
grad-zadar.hr,"HTTPSConnectionPool(host='grad-zadar.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9670669580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grad-zadar.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96681756d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gradja.hr,"HTTPSConnectionPool(host='gradja.hr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='gradja.hr', port=80): Read timed out. (read timeout=2)"
gramatnicaglobuss.lv,"HTTPSConnectionPool(host='gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)"
grazia.it,"HTTPSConnectionPool(host='grazia.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9667e960d0>, 'Connection to grazia.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='grazia.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9669a03430>, 'Connection to grazia.it timed out. (connect timeout=2)'))"
graziadaily.co.uk,"HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)"
grizly.cz,"HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)"
grizly.sk,"HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)"
gruene.at,"HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)"
grupolusofona.pt,"HTTPSConnectionPool(host='grupolusofona.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966eea2c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grupolusofona.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96700fb580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gsb.gov.tr,"HTTPSConnectionPool(host='gsb.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f966a526ca0>, 'Connection to gsb.gov.tr timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='gsb.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f966edfacd0>, 'Connection to gsb.gov.tr timed out. (connect timeout=2)'))"
gsb.or.th,"HTTPSConnectionPool(host='gsb.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966c04fd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gsb.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f966c298cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gtp.gr,"HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))","HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))"
guaranteepra.com,"HTTPSConnectionPool(host='guaranteepra.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9671411190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='guaranteepra.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96721efd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
guiadelocio.com,"HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)"
guiagt.com,"HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)"
guiato.com.br,"HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gunadarma.ac.id,"HTTPSConnectionPool(host='gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
guru.ua,"HTTPSConnectionPool(host='guru.ua', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='guru.ua', port=80): Read timed out. (read timeout=2)"
gustissimo.it,"HTTPSConnectionPool(host='gustissimo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.gustissimo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
guzzle.co.za,"HTTPSConnectionPool(host='guzzle.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'guzzle.co.za' doesn't match 'www.guzzle.co.za'"")))","HTTPSConnectionPool(host='www.guzzle.co.za', port=443): Read timed out. (read timeout=2)"
gyorplusz.hu,"HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)"
gzt.com,"HTTPSConnectionPool(host='www.gzt.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gzt.com', port=443): Read timed out. (read timeout=2)"
ha.rs,"HTTPSConnectionPool(host='ha.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f96697f7130>, 'Connection to ha.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ha.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f96728d4c70>, 'Connection to ha.rs timed out. (connect timeout=2)'))"
hacienda.go.cr,"HTTPSConnectionPool(host='hacienda.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f966ef1abb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPSConnectionPool(host='www.hacienda.go.cr', port=443): Read timed out. (read timeout=2)"
haifa.ac.il,"HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
hakolhayehudi.co.il,"HTTPSConnectionPool(host='hakolhayehudi.co.il', port=443): Read timed out.","HTTPConnectionPool(host='hakolhayehudi.co.il', port=80): Read timed out."
hamazo.tv,"HTTPSConnectionPool(host='hamazo.tv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.hamazo.tv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
