iaen.edu.ec,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
iainbengkulu.ac.id,"HTTPSConnectionPool(host='iainbengkulu.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='iainbengkulu.ac.id', port=443): Read timed out. (read timeout=2)"
iainkediri.ac.id,"HTTPSConnectionPool(host='iainkediri.ac.id', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='iainkediri.ac.id', port=80): Read timed out. (read timeout=2)"
iam.ma,"HTTPSConnectionPool(host='iam.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='iam.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb178156a0>, 'Connection to iam.ma timed out. (connect timeout=2)'))"
ias.co.il,"HTTPSConnectionPool(host='ias.co.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ias.co.il', port=80): Read timed out. (read timeout=2)"
ibict.br,"HTTPSConnectionPool(host='ibict.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ibict.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
icbc.com.ar,"HTTPSConnectionPool(host='icbc.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='icbc.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
icbf.gov.co,"HTTPSConnectionPool(host='icbf.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb1798af40>, 'Connection to icbf.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='icbf.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb15f666d0>, 'Connection to icbf.gov.co timed out. (connect timeout=2)'))"
icm.edu.pl,"HTTPSConnectionPool(host='icm.edu.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='icm.edu.pl', port=443): Read timed out. (read timeout=2)"
iconmagazine.it,"HTTPSConnectionPool(host='www.iconmagazine.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.iconmagazine.it', port=443): Read timed out. (read timeout=2)"
idi.org.il,"HTTPSConnectionPool(host='idi.org.il', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb160e1280>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='idi.org.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb14e41fa0>, 'Connection to idi.org.il timed out. (connect timeout=2)'))"
ieatishootipost.sg,"HTTPConnectionPool(host='ieatishootipost.sg', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ieatishootipost.sg', port=80): Read timed out. (read timeout=2)"
iedu.sk,"HTTPSConnectionPool(host='iedu.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='iedu.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
iefp.pt,"HTTPSConnectionPool(host='iefp.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb13513670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='iefp.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb14c446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ieftine.eu,Exceeded 30 redirects.,Exceeded 30 redirects.
iett.istanbul,"HTTPSConnectionPool(host='iett.istanbul', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='iett.istanbul', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
igm.org.il,"HTTPSConnectionPool(host='igm.org.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='igm.org.il', port=80): Read timed out. (read timeout=2)"
iho.hu,"HTTPSConnectionPool(host='iho.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='iho.hu', port=443): Read timed out. (read timeout=2)"
iif.hu,"HTTPSConnectionPool(host='iif.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb12d9a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='iif.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb153a7c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ijf.hr,"HTTPSConnectionPool(host='ijf.hr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb11ef5eb0>, 'Connection to ijf.hr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ijf.hr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb13336a00>, 'Connection to ijf.hr timed out. (connect timeout=2)'))"
ijunoon.com,"HTTPSConnectionPool(host='ijunoon.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ijunoon.com', port=443): Read timed out. (read timeout=2)"
ilkha.com,"HTTPSConnectionPool(host='ilkha.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ilkha.com', port=443): Read timed out. (read timeout=2)"
ilmangione.it,"HTTPSConnectionPool(host='ilmangione.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ilmangione.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ilmusosial.id,"HTTPSConnectionPool(host='ilmusosial.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb17629c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ilmusosial.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb116b4250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
imamu.edu.sa,"HTTPSConnectionPool(host='imamu.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='imamu.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
imge.com.tr,"HTTPSConnectionPool(host='imge.com.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb0f2b3640>, 'Connection to imge.com.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='imge.com.tr', port=80): Read timed out. (read timeout=2)"
imged.pl,"HTTPSConnectionPool(host='imged.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb1705cf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='imged.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb14e41d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
imist.ma,"HTTPSConnectionPool(host='imist.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb159af370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='imist.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb182a4160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
immoproxio.be,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
imprentanacional.go.cr,"HTTPSConnectionPool(host='imprentanacional.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0f9c6cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='imprentanacional.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb12da50a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
impreseita.com,"HTTPSConnectionPool(host='impreseita.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb143754c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='impreseita.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb0eeda9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
imt-ip.pt,"HTTPSConnectionPool(host='imt-ip.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb16ec02e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='imt-ip.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb0ec97340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
imtranslator.net,"HTTPSConnectionPool(host='imtranslator.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='imtranslator.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
imunita.online,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
inafed.gob.mx,"HTTPSConnectionPool(host='inafed.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb18c8caf0>, 'Connection to inafed.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='inafed.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb0ec97070>, 'Connection to inafed.gob.mx timed out. (connect timeout=2)'))"
inclusion.gob.ec,"HTTPSConnectionPool(host='inclusion.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'inclusion.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
indap.gob.cl,"('Connection aborted.', BadStatusLine('\n'))","HTTPConnectionPool(host='www.indap.gob.cl', port=80): Read timed out. (read timeout=2)"
indexlivingmall.com,"HTTPSConnectionPool(host='indexlivingmall.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb0e8679d0>, 'Connection to indexlivingmall.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='indexlivingmall.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb17cd63a0>, 'Connection to indexlivingmall.com timed out. (connect timeout=2)'))"
indiacom.com,"HTTPSConnectionPool(host='indiacom.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb15efec70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='indiacom.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb1646a160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
indonesia.go.id,"HTTPSConnectionPool(host='indonesia.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.indonesia.go.id', port=443): Read timed out. (read timeout=2)"
ine.gob.gt,"HTTPSConnectionPool(host='ine.gob.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ine.gob.gt' doesn't match 'www.ine.gob.gt'"")))","HTTPSConnectionPool(host='www.ine.gob.gt', port=443): Read timed out. (read timeout=2)"
ine.gub.uy,"HTTPSConnectionPool(host='ine.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ine.gub.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb1600b5b0>, 'Connection to ine.gub.uy timed out. (connect timeout=2)'))"
inefop.org.uy,"HTTPSConnectionPool(host='inefop.org.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0ecaa8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='inefop.org.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb0ebff970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
infarmed.pt,"HTTPSConnectionPool(host='infarmed.pt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb1168e310>, 'Connection to infarmed.pt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='infarmed.pt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb0e79cd90>, 'Connection to infarmed.pt timed out. (connect timeout=2)'))"
infinitydesign.in.th,"HTTPSConnectionPool(host='www.infinitydesign.in.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.infinitydesign.in.th', port=443): Read timed out. (read timeout=2)"
infocenters.co.il,"HTTPSConnectionPool(host='infocenters.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='infocenters.co.il', port=443): Read timed out. (read timeout=2)"
infogate.cl,"HTTPSConnectionPool(host='www.infogate.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='infogate.cl', port=443): Read timed out. (read timeout=2)"
infoguia.co.cr,"HTTPSConnectionPool(host='infoguia.co.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb1554b130>, 'Connection to infoguia.co.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='infoguia.co.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb0e873f40>, 'Connection to infoguia.co.cr timed out. (connect timeout=2)'))"
infoguia.com,"HTTPSConnectionPool(host='infoguia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb0eacedf0>, 'Connection to infoguia.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='infoguia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb167b8610>, 'Connection to infoguia.com timed out. (connect timeout=2)'))"
infojuht.ee,"HTTPSConnectionPool(host='infojuht.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='infojuht.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
infomed.co.il,"HTTPSConnectionPool(host='infomed.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb1798a7c0>, 'Connection to infomed.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='infomed.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb1308b610>, 'Connection to infomed.co.il timed out. (connect timeout=2)'))"
infonegocios.biz,"HTTPSConnectionPool(host='infonegocios.biz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='infonegocios.biz', port=443): Read timed out. (read timeout=2)"
infonegocios.info,"HTTPSConnectionPool(host='infonegocios.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='infonegocios.info', port=443): Read timed out. (read timeout=2)"
infoprision.com,"HTTPSConnectionPool(host='infoprision.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'infoprision.com' doesn't match 'www.infoprision.com'"")))","HTTPSConnectionPool(host='infoprision.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'infoprision.com' doesn't match 'www.infoprision.com'"")))"
infoproff.com,"HTTPSConnectionPool(host='infoproff.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.infoproff.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
infopublik.id,"HTTPSConnectionPool(host='infopublik.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='infopublik.id', port=443): Read timed out. (read timeout=2)"
informa.es,"HTTPSConnectionPool(host='www.informa.es', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.informa.es', port=443): Read timed out. (read timeout=2)"
information.dk,"HTTPSConnectionPool(host='information.dk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.information.dk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
ing.be,"HTTPSConnectionPool(host='ing.be', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ing.be', port=80): Read timed out. (read timeout=2)"
ingatlantajolo.hu,"HTTPSConnectionPool(host='www.ingatlantajolo.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ingatlantajolo.hu', port=443): Read timed out. (read timeout=2)"
ins-cr.com,"HTTPSConnectionPool(host='ins-cr.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0e3208e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ins-cr.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb176b84c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
insee.fr,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
interbuh.com.ua,"HTTPSConnectionPool(host='interbuh.com.ua', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='interbuh.com.ua', port=443): Read timed out. (read timeout=2)"
intermarche.pt,"HTTPSConnectionPool(host='www.intermarche.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.intermarche.pt', port=443): Read timed out. (read timeout=2)"
internimedicina.cz,"HTTPSConnectionPool(host='internimedicina.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='internimedicina.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
intima.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
investireoggi.it,"HTTPSConnectionPool(host='www.investireoggi.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.investireoggi.it', port=443): Read timed out. (read timeout=2)"
invima.gov.co,"HTTPSConnectionPool(host='invima.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='invima.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
io.ua,"HTTPSConnectionPool(host='io.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0e3a08b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='io.ua', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb0b04d4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ioc.ee,"HTTPSConnectionPool(host='ioc.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ioc.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ipapercms.dk,"HTTPSConnectionPool(host='ipapercms.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0e76c820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ipapercms.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb153b9b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ipleaders.in,"HTTPSConnectionPool(host='ipleaders.in', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ipleaders.in', port=443): Read timed out. (read timeout=2)"
ipleiria.pt,"HTTPSConnectionPool(host='ipleiria.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ipleiria.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ipoor.org,"HTTPSConnectionPool(host='ipoor.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb16ff3af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ipoor.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb16a6b7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ipsantarem.pt,"HTTPSConnectionPool(host='ipsantarem.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb155165b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ipsantarem.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb0e20b4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ipst.ac.th,"HTTPSConnectionPool(host='ipst.ac.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb18101310>, 'Connection to ipst.ac.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ipst.ac.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb154bec10>, 'Connection to ipst.ac.th timed out. (connect timeout=2)'))"
ipvc.pt,"HTTPSConnectionPool(host='ipvc.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb0e9719a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ipvc.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb11627d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ir.lv,"HTTPSConnectionPool(host='ir.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ir.lv', port=443): Read timed out. (read timeout=2)"
ird.gov.lk,"HTTPSConnectionPool(host='ird.gov.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb17f432b0>: Failed to establish a new connection: [Errno 113] No route to host'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
