lahiguera.net,"HTTPSConnectionPool(host='lahiguera.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.lahiguera.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lahloba.com,"HTTPSConnectionPool(host='www.lahloba.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lahloba.com', port=443): Read timed out. (read timeout=2)"
lahora.gt,"HTTPSConnectionPool(host='lahora.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lahora.gt', port=443): Read timed out. (read timeout=2)"
lallina.it,"HTTPSConnectionPool(host='lallina.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='lallina.it', port=80): Read timed out. (read timeout=2)"
land.gov.il,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPSConnectionPool(host='www.gov.il', port=443): Max retries exceeded with url: /he/departments/israel_land_authority (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f044245ceb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
laosprocessservers.com,"HTTPSConnectionPool(host='laosprocessservers.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='laosprocessservers.com', port=80): Read timed out. (read timeout=2)"
lapaz.bo,"HTTPSConnectionPool(host='lapaz.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0444a79e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lapaz.bo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0441ee1e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
larebajavirtual.com,"HTTPSConnectionPool(host='larebajavirtual.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='larebajavirtual.com', port=443): Read timed out. (read timeout=2)"
lascondes.cl,"HTTPSConnectionPool(host='lascondes.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.lascondes.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lasegunda.com,"HTTPSConnectionPool(host='lasegunda.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0442f30ca0>, 'Connection to lasegunda.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='lasegunda.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0443024730>, 'Connection to lasegunda.com timed out. (connect timeout=2)'))"
lasering.ee,"HTTPSConnectionPool(host='www.lasering.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lasering.ee', port=443): Read timed out. (read timeout=2)"
lavoiedushangrila.be,"HTTPSConnectionPool(host='lavoiedushangrila.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0444345430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lavoiedushangrila.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0445580430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lavprisvvs.dk,"HTTPSConnectionPool(host='www.lavprisvvs.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lavprisvvs.dk', port=443): Read timed out. (read timeout=2)"
lcb.lv,"HTTPSConnectionPool(host='lcb.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f04448ab490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lcb.lv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0443358c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ldb.lt,"HTTPSConnectionPool(host='ldb.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0443939bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ldb.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f043edb3dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ldblog.jp,"HTTPSConnectionPool(host='ldblog.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f044432b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ldblog.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04438e48b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ldoceonline.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
le.ee,"HTTPSConnectionPool(host='le.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'le.ee' doesn't match either of '*.tll07.zoneas.eu', 'tll07.zoneas.eu'"")))","HTTPSConnectionPool(host='online.le.ee', port=443): Read timed out. (read timeout=2)"
leading-talents.com,"HTTPConnectionPool(host='www.leading-talents.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.leading-talents.com', port=80): Read timed out. (read timeout=2)"
led.go.th,"HTTPSConnectionPool(host='led.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0446015760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='led.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f043db4d550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
leggioggi.it,"HTTPSConnectionPool(host='leggioggi.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f04440a6040>, 'Connection to leggioggi.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='leggioggi.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f043db64e80>, 'Connection to leggioggi.it timed out. (connect timeout=2)'))"
lekabobgrill.com,"HTTPSConnectionPool(host='lekabobgrill.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='lekabobgrill.com', port=80): Read timed out. (read timeout=2)"
lekari.sk,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
lengua-e.com,"HTTPSConnectionPool(host='lengua-e.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0443ee73a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lengua-e.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f044187d880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lenouvelliste.ch,"HTTPSConnectionPool(host='lenouvelliste.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.lenouvelliste.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
lepetitjournal.com,"HTTPSConnectionPool(host='lepetitjournal.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lepetitjournal.com', port=443): Read timed out. (read timeout=2)"
lerobert.com,"HTTPSConnectionPool(host='lerobert.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='lerobert.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
leseco.ma,"HTTPSConnectionPool(host='leseco.ma', port=443): Read timed out.","HTTPConnectionPool(host='leseco.ma', port=80): Read timed out. (read timeout=2)"
leto.gr,"HTTPSConnectionPool(host='leto.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f043c8a8100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='leto.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f043c5d6af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
letras4u.com,"HTTPSConnectionPool(host='letras4u.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.letras4u.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
letssingit.com,"HTTPSConnectionPool(host='letssingit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0444e95d30>, 'Connection to letssingit.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='letssingit.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f04403c1be0>, 'Connection to letssingit.com timed out. (connect timeout=2)'))"
leumi.co.il,"HTTPSConnectionPool(host='leumi.co.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='leumi.co.il', port=80): Read timed out. (read timeout=2)"
lex-localis.info,"HTTPSConnectionPool(host='lex-localis.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0445770d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lex-localis.info', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0444fb1070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lex.pl,"HTTPSConnectionPool(host='lex.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.lex.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
leychile.cl,"HTTPSConnectionPool(host='leychile.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f043c099730>, 'Connection to leychile.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='leychile.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0442f30970>, 'Connection to leychile.cl timed out. (connect timeout=2)'))"
lgov.hu,"HTTPSConnectionPool(host='lgov.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0443906130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lgov.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0444603d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
liberation.fr,"HTTPSConnectionPool(host='liberation.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='liberation.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
librariaonline.ro,"HTTPSConnectionPool(host='www.librariaonline.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.librariaonline.ro', port=443): Read timed out. (read timeout=2)"
librarything.es,"HTTPSConnectionPool(host='librarything.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'librarything.es' doesn't match either of 'www.librarything.de', 'www.librarything.es', 'www.librarything.fr', 'www.librarything.it', 'www.librarything.nl'"")))","HTTPSConnectionPool(host='librarything.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'librarything.es' doesn't match either of 'www.librarything.de', 'www.librarything.es', 'www.librarything.fr', 'www.librarything.it', 'www.librarything.nl'"")))"
lielvarde.lv,"HTTPSConnectionPool(host='lielvarde.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0446280cd0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='lielvarde.lv', port=80): Read timed out. (read timeout=2)"
lifegate.it,"HTTPSConnectionPool(host='lifegate.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.lifegate.it', port=443): Read timed out. (read timeout=2)"
lifehacker.jp,"HTTPSConnectionPool(host='www.lifehacker.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lifehacker.jp', port=443): Read timed out. (read timeout=2)"
ligavam.lv,"HTTPSConnectionPool(host='ligavam.lv', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ligavam.lv', port=80): Read timed out. (read timeout=2)"
lilafuge.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
lineconomi.me,"HTTPSConnectionPool(host='lineconomi.me', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lineconomi.me', port=443): Read timed out. (read timeout=2)"
linkly.co.il,"HTTPSConnectionPool(host='linkly.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='linkly.co.il', port=443): Read timed out. (read timeout=2)"
lippu.fi,"HTTPSConnectionPool(host='www.lippu.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.lippu.fi', port=80): Read timed out. (read timeout=2)"
lirabrannon.com,"HTTPConnectionPool(host='www.lirabrannon.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.lirabrannon.com', port=80): Read timed out. (read timeout=2)"
listafirme.ro,Exceeded 30 redirects.,Exceeded 30 redirects.
litoralpress.cl,"HTTPConnectionPool(host='www.litoralpress.cl', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='litoralpress.cl', port=80): Read timed out. (read timeout=2)"
litteraturmagazinet.se,"HTTPSConnectionPool(host='litteraturmagazinet.se', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f04452037f0>, 'Connection to litteraturmagazinet.se timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.litteraturmagazinet.se', port=80): Read timed out. (read timeout=2)"
livedoor.biz,"HTTPSConnectionPool(host='livedoor.biz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f04435b9be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='livedoor.biz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f044282ae80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
livedoor.blog,"HTTPSConnectionPool(host='livedoor.blog', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f043dae45e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='livedoor.blog', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0438cec280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
livefans.jp,"HTTPSConnectionPool(host='livefans.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'livefans.jp' doesn't match '*.livefans.jp'"")))","HTTPConnectionPool(host='www.livefans.jp', port=80): Read timed out. (read timeout=2)"
livelib.ru,"HTTPSConnectionPool(host='www.livelib.ru', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.livelib.ru', port=443): Read timed out. (read timeout=2)"
livescience.com,"HTTPSConnectionPool(host='livescience.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f04396e0cd0>, 'Connection to livescience.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='livescience.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f043960f760>, 'Connection to livescience.com timed out. (connect timeout=2)'))"
livinginsider.com,"HTTPSConnectionPool(host='livinginsider.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.livinginsider.com', port=443): Read timed out. (read timeout=2)"
llti.lt,"HTTPSConnectionPool(host='llti.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'llti.lt' doesn't match either of 'radius.llti.lt', 'ldap.llti.lt', 'kolab.llti.lt', 'smtp.llti.lt', 'pop3.llti.lt', 'imap.llti.lt', 'wmail.llti.lt', 'mail.llti.lt'"")))","HTTPSConnectionPool(host='wmail.llti.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
lmaga.jp,"HTTPSConnectionPool(host='www.lmaga.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lmaga.jp', port=443): Read timed out. (read timeout=2)"
lmta.lt,"HTTPSConnectionPool(host='lmta.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='lmta.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
