praktis.bg,"HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prathaprachan-mag.com,"HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)"
pravatami.bg,"HTTPSConnectionPool(host='pravatami.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pravatami.bg', port=443): Read timed out. (read timeout=2)"
precos.lv,"HTTPSConnectionPool(host='precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pref.aichi.jp,"HTTPSConnectionPool(host='pref.aichi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc4104cf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.aichi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc403eb9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.gunma.jp,"HTTPSConnectionPool(host='pref.gunma.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3f13d730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.gunma.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc40557a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.ibaraki.jp,"HTTPSConnectionPool(host='pref.ibaraki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3f28cd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.ibaraki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc40155220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kagoshima.jp,"HTTPSConnectionPool(host='pref.kagoshima.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc40c97e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kagoshima.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3fd8c760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kanagawa.jp,"HTTPSConnectionPool(host='pref.kanagawa.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc415cb400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kanagawa.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3fc844f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kyoto.jp,"HTTPSConnectionPool(host='pref.kyoto.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc4163bc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kyoto.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3f9b0d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.miyagi.jp,"HTTPSConnectionPool(host='pref.miyagi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3fd8c6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.miyagi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3f8287f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.nara.jp,"HTTPSConnectionPool(host='pref.nara.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc4044dee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.nara.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3f34a940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.okayama.jp,"HTTPSConnectionPool(host='pref.okayama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3f2802b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.okayama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3f2808e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.shizuoka.jp,"HTTPSConnectionPool(host='pref.shizuoka.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3f34a0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.shizuoka.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3ee6fd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
preissuchmaschine.de,"HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prensalibre.com,"HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out.","HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out."
presidencia.go.cr,"HTTPSConnectionPool(host='presidencia.go.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='presidencia.go.cr', port=80): Read timed out. (read timeout=2)"
presidencia.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
pressbooks.pub,"HTTPSConnectionPool(host='pressbooks.pub', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pressbooks.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
priberam.org,"HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))","HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))"
pricee.vn,"HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out. (read timeout=2)"
pricespy.co.nz,"HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)"
pricesworld.net,"HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out.","HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out."
prijs-trappen.be,"HTTPSConnectionPool(host='prijs-trappen.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3ce60700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='prijs-trappen.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3dc9edc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prim.lt,"HTTPSConnectionPool(host='prim.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3fb47820>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.prim.lt', port=80): Read timed out. (read timeout=2)"
primabazar.cz,"HTTPSConnectionPool(host='primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
priyoshop.com,"HTTPSConnectionPool(host='priyoshop.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='priyoshop.com', port=443): Read timed out. (read timeout=2)"
prnewswire.com,"HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
procuraduria.gov.co,"HTTPSConnectionPool(host='procuraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3f71fd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='procuraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc3b3ddac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
profiremont.sk,"HTTPSConnectionPool(host='profiremont.sk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='profiremont.sk', port=80): Read timed out. (read timeout=2)"
promenad.hu,"HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)"
promenadanovisad.rs,"HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='promenadanovisad.rs', port=80): Read timed out. (read timeout=2)"
promerica.fi.cr,"HTTPSConnectionPool(host='promerica.fi.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc40cb91c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='promerica.fi.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc40f02b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promodirecta.com.ar,"HTTPSConnectionPool(host='promodirecta.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='www.promodirecta.com.ar', port=80): Read timed out. (read timeout=2)"
propisi.com,"HTTPSConnectionPool(host='propisi.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='propisi.com', port=80): Read timed out. (read timeout=2)"
propmark.com.br,"HTTPSConnectionPool(host='propmark.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='propmark.com.br', port=443): Read timed out. (read timeout=2)"
proshareng.com,"HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)"
protexin.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
protoporia.gr,"HTTPSConnectionPool(host='protoporia.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'protoporia.gr' doesn't match 'www.protoporia.gr'"")))",Exceeded 30 redirects.
provincia.tn.it,"HTTPSConnectionPool(host='provincia.tn.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3fd1c220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provincia.tn.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc39d1d7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
provisible.nl,"HTTPSConnectionPool(host='provisible.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc379baf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provisible.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc37995400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prtfl.co.il,"HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)"
psau.edu.sa,"HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
psd.gov.jo,"HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
psiquiatria.com,"HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)"
pta.gov.pk,"HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ptt.gov.tr,"HTTPSConnectionPool(host='ptt.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc3ce84640>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ptt.gov.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc40e072e0>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))"
pub.ro,"HTTPSConnectionPool(host='pub.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3b964d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pub.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc41cf5b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
public-welfare.com,"HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)"
publiciudad.cl,"HTTPSConnectionPool(host='publiciudad.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc44e578b0>, 'Connection to publiciudad.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='publiciudad.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc3e881b20>, 'Connection to publiciudad.cl timed out. (connect timeout=2)'))"
publinews.gt,"HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)"
publishing.service.gov.uk,"HTTPSConnectionPool(host='publishing.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc42060790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='publishing.service.gov.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc409a7ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puc-rio.br,"HTTPSConnectionPool(host='puc-rio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc39827b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puc-rio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc38ec19d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puce.edu.ec,"HTTPSConnectionPool(host='puce.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc410b5520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puce.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc37a6f040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pucgoias.edu.br,"HTTPSConnectionPool(host='pucgoias.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc3b7f2250>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pucgoias.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc40067a30>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))"
pucminas.br,"HTTPSConnectionPool(host='pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
punjab.gov.pk,"HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc41fbaaf0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='punjab.gov.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc40f530a0>: Failed to establish a new connection: [Errno 113] No route to host'))"
pupulandia.fi,"HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)"
pycca.com,"HTTPSConnectionPool(host='pycca.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3c396b80>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pycca.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc37de67f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pylimas.lt,"HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
qatips.net,"HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)"
quedigital.com.ar,"HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)"
quito.gob.ec,"HTTPSConnectionPool(host='quito.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quito.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc3fc848e0>, 'Connection to quito.gob.ec timed out. (connect timeout=2)'))"
quochoi.vn,"HTTPSConnectionPool(host='quochoi.vn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc3fee4d00>, 'Connection to quochoi.vn timed out. (connect timeout=2)'))","('Connection aborted.', UnknownProtocol('HTTP/'))"
raanana.muni.il,"HTTPSConnectionPool(host='raanana.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc37995af0>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='raanana.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc381b79a0>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))"
rabota.ru,"HTTPSConnectionPool(host='rabota.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc40bf6e80>, 'Connection to rabota.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rabota.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdc3f27e0d0>, 'Connection to rabota.ru timed out. (connect timeout=2)'))"
radiokim.net,"HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)"
radiomundial.com.ve,"HTTPSConnectionPool(host='radiomundial.com.ve', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc403618b0>, 'Connection to radiomundial.com.ve timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomundial.com.ve', port=80): Read timed out. (read timeout=2)"
radiopopular.pt,"HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))","HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))"
radioromaniacultural.ro,"HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out.","HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out."
radiosago.cl,"HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)"
radiosantafe.com,"HTTPSConnectionPool(host='radiosantafe.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiosantafe.com' doesn't match 'www.radiosantafe.com'"")))","HTTPConnectionPool(host='radiosantafe.com', port=80): Read timed out. (read timeout=2)"
rafeeg.ae,"HTTPSConnectionPool(host='www.rafeeg.ae', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rafeeg.ae', port=443): Read timed out. (read timeout=2)"
raiceshandcrafts.com,"HTTPConnectionPool(host='www.stuartvener.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.stuartvener.com', port=80): Read timed out. (read timeout=2)"
raiffeisen.ro,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))"
rakuten.co.jp,"HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)"
rakuten.com.tw,"HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)"
rakuten.ne.jp,"HTTPSConnectionPool(host='rakuten.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc3c59bca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rakuten.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc409634f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ramajudicial.gov.co,"HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rchsd.org,"HTTPSConnectionPool(host='rchsd.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc398778e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rchsd.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc4094d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rdpad.lv,"HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rdvmedicaux.com,"HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))","HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))"
