praktis.bg,"HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prathaprachan-mag.com,"HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)"
pravatami.bg,"HTTPSConnectionPool(host='pravatami.bg', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='pravatami.bg', port=80): Read timed out. (read timeout=2)"
precos.lv,"HTTPSConnectionPool(host='precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pref.aichi.jp,"HTTPSConnectionPool(host='pref.aichi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db8a93fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.aichi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db9e1e8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.gunma.jp,"HTTPSConnectionPool(host='pref.gunma.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db89c44c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.gunma.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db9f61fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.ibaraki.jp,"HTTPSConnectionPool(host='pref.ibaraki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db941d4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.ibaraki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db9af6460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kagoshima.jp,"HTTPSConnectionPool(host='pref.kagoshima.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db8b83fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kagoshima.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db97326d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kanagawa.jp,"HTTPSConnectionPool(host='pref.kanagawa.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dba79f670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kanagawa.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db9635100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kyoto.jp,"HTTPSConnectionPool(host='pref.kyoto.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dba472df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kyoto.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db941d730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.miyagi.jp,"HTTPSConnectionPool(host='pref.miyagi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dba3d6790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.miyagi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db91e5b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.nara.jp,"HTTPSConnectionPool(host='pref.nara.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dbbce67c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.nara.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db8c43b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.okayama.jp,"HTTPSConnectionPool(host='pref.okayama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db8b76730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.okayama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db8b78b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.shizuoka.jp,"HTTPSConnectionPool(host='pref.shizuoka.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db8c43d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.shizuoka.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db8884820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
preissuchmaschine.de,"HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
presidencia.go.cr,"HTTPSConnectionPool(host='presidencia.go.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='presidencia.go.cr', port=80): Read timed out. (read timeout=2)"
presidencia.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
pressbooks.pub,"HTTPSConnectionPool(host='pressbooks.pub', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pressbooks.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
priberam.org,"HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))","HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))"
pricepulse.app,"HTTPSConnectionPool(host='www.pricepulse.app', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pricepulse.app', port=443): Read timed out. (read timeout=2)"
pricespy.co.nz,"HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)"
pricesworld.net,"HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out.","HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out."
prijs-trappen.be,"HTTPSConnectionPool(host='prijs-trappen.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db9e1eee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='prijs-trappen.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db7e18310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prim.lt,"HTTPSConnectionPool(host='prim.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db75d7430>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.prim.lt', port=80): Read timed out. (read timeout=2)"
primabazar.cz,"HTTPSConnectionPool(host='primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
priyoshop.com,"HTTPSConnectionPool(host='priyoshop.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='priyoshop.com', port=443): Read timed out. (read timeout=2)"
prnewswire.com,"HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
procuraduria.gov.co,"HTTPSConnectionPool(host='procuraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db92300d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='procuraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db54837f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
profital.ch,"HTTPSConnectionPool(host='www.profital.ch', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.profital.ch', port=443): Read timed out. (read timeout=2)"
promenad.hu,"HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)"
promenadanovisad.rs,"HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)"
promerica.fi.cr,"HTTPSConnectionPool(host='promerica.fi.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db8dc1d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='promerica.fi.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db5281dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promodirecta.com.ar,"HTTPSConnectionPool(host='promodirecta.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='www.promodirecta.com.ar', port=80): Read timed out. (read timeout=2)"
property.com.au,"HTTPSConnectionPool(host='www.property.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.property.com.au', port=443): Read timed out. (read timeout=2)"
propisi.com,"HTTPSConnectionPool(host='propisi.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='propisi.com', port=80): Read timed out. (read timeout=2)"
proshareng.com,"HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)"
protexin.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
provincia.tn.it,"HTTPSConnectionPool(host='provincia.tn.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db7e8c0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provincia.tn.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db1feca00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
provisible.nl,"HTTPSConnectionPool(host='provisible.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db13abfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provisible.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7dbb28a2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prtfl.co.il,"HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)"
pruksa.com,"HTTPSConnectionPool(host='www.pruksa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pruksa.com', port=443): Read timed out. (read timeout=2)"
psau.edu.sa,"HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
psd.gov.jo,"HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
psiquiatria.com,"HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)"
pta.gov.pk,"HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ptt.gov.tr,"HTTPSConnectionPool(host='ptt.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db9e0c610>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ptt.gov.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7db12fce50>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))"
pub.ro,"HTTPSConnectionPool(host='pub.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db9035d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pub.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db04cc130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
publinews.gt,"HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)"
publishing.service.gov.uk,"HTTPSConnectionPool(host='publishing.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dbb7b9700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='publishing.service.gov.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7dba1c63a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puc-rio.br,"HTTPSConnectionPool(host='puc-rio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db9501790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puc-rio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db52ed2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puce.edu.ec,"HTTPSConnectionPool(host='puce.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dba0f7f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puce.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db5efc220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pucgoias.edu.br,"HTTPSConnectionPool(host='pucgoias.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db52818b0>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pucgoias.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7dbb874460>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))"
pucminas.br,"HTTPSConnectionPool(host='pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pulzo.com,"HTTPSConnectionPool(host='pulzo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db05b0340>, 'Connection to pulzo.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pulzo.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7db11d6820>, 'Connection to pulzo.com timed out. (connect timeout=2)'))"
punjab.gov.pk,"HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db1f11b20>, 'Connection to punjab.gov.pk timed out. (connect timeout=2)'))","HTTPConnectionPool(host='punjab.gov.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db059e430>: Failed to establish a new connection: [Errno 113] No route to host'))"
pupulandia.fi,"HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)"
putereaplantelor.ro,"HTTPSConnectionPool(host='www.putereaplantelor.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.putereaplantelor.ro', port=443): Read timed out. (read timeout=2)"
pycca.com,"HTTPSConnectionPool(host='pycca.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db0503ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pycca.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db7641f70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pylimas.lt,"HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
qatips.net,"HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)"
qaym.com,"HTTPSConnectionPool(host='qaym.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qaym.com', port=443): Read timed out. (read timeout=2)"
quadratin.com.mx,"HTTPSConnectionPool(host='quadratin.com.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quadratin.com.mx', port=443): Read timed out. (read timeout=2)"
quedigital.com.ar,"HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)"
quito.gob.ec,"HTTPSConnectionPool(host='quito.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quito.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7dbace0a90>, 'Connection to quito.gob.ec timed out. (connect timeout=2)'))"
quus.net,"HTTPSConnectionPool(host='quus.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quus.net', port=80): Read timed out. (read timeout=2)"
ra.ee,"HTTPSConnectionPool(host='ra.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ra.ee' doesn't match 'www.ra.ee'"")))","HTTPSConnectionPool(host='www.ra.ee', port=443): Read timed out. (read timeout=2)"
raanana.muni.il,"HTTPSConnectionPool(host='raanana.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db1e83f10>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='raanana.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7db8ec7ac0>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))"
rabota.ru,"HTTPSConnectionPool(host='www.rabota.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7db942ce50>, 'Connection to www.rabota.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rabota.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7db1d9db20>, 'Connection to rabota.ru timed out. (connect timeout=2)'))"
radiomundial.com.ve,"HTTPSConnectionPool(host='radiomundial.com.ve', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7dba52a8b0>, 'Connection to radiomundial.com.ve timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomundial.com.ve', port=80): Read timed out. (read timeout=2)"
radiopopular.pt,"HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))","HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))"
radioromaniacultural.ro,"HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out.","HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out."
radiosago.cl,"HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)"
radiosantafe.com,"HTTPSConnectionPool(host='radiosantafe.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiosantafe.com' doesn't match 'www.radiosantafe.com'"")))","HTTPConnectionPool(host='radiosantafe.com', port=80): Read timed out. (read timeout=2)"
rae.ee,"HTTPSConnectionPool(host='rae.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rae.ee' doesn't match either of '*.kovtp.ee', 'kovtp.ee'"")))","HTTPSConnectionPool(host='www.rae.ee', port=443): Read timed out. (read timeout=2)"
raiffeisen.ro,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))"
rakuten.co.jp,"HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)"
rakuten.com.tw,"HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)"
rakuten.ne.jp,"HTTPSConnectionPool(host='rakuten.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db25e8a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rakuten.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db9c59580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ramajudicial.gov.co,"HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rapina.ee,"HTTPSConnectionPool(host='rapina.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rapina.ee' doesn't match either of '*.kovtp.ee', 'kovtp.ee'"")))","HTTPSConnectionPool(host='www.rapina.ee', port=443): Read timed out. (read timeout=2)"
rayhon.me,"HTTPSConnectionPool(host='rayhon.me', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='rayhon.me', port=443): Read timed out. (read timeout=2)"
rchsd.org,"HTTPSConnectionPool(host='rchsd.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7db87adb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rchsd.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7db686d130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rdpad.lv,"HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rdvmedicaux.com,"HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))","HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))"
