prakardproperty.com,"HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)"
praktis.bg,"HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prathaprachan-mag.com,"HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)"
precos.lv,"HTTPSConnectionPool(host='precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pref.aichi.jp,"HTTPSConnectionPool(host='pref.aichi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddf5a8fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.aichi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dddd36d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.gunma.jp,"HTTPSConnectionPool(host='pref.gunma.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddcc69a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.gunma.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddf446370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.ibaraki.jp,"HTTPSConnectionPool(host='pref.ibaraki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddc8d8910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.ibaraki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dddbd4b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kagoshima.jp,"HTTPSConnectionPool(host='pref.kagoshima.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dde5381c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kagoshima.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddd8315b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kanagawa.jp,"HTTPSConnectionPool(host='pref.kanagawa.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddcc69bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kanagawa.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddd6b60d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kyoto.jp,"HTTPSConnectionPool(host='pref.kyoto.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddc860b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kyoto.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddd444940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.miyagi.jp,"HTTPSConnectionPool(host='pref.miyagi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddd708fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.miyagi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddd1f6970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.nara.jp,"HTTPSConnectionPool(host='pref.nara.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dde3e1ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.nara.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddcc69e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.okayama.jp,"HTTPSConnectionPool(host='pref.okayama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddd708fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.okayama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddcafbf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.shizuoka.jp,"HTTPSConnectionPool(host='pref.shizuoka.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddcc694c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.shizuoka.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddc860d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
preissuchmaschine.de,"HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prensalibre.com,"HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out.","HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out."
presidencia.go.cr,"HTTPSConnectionPool(host='presidencia.go.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='presidencia.go.cr', port=80): Read timed out. (read timeout=2)"
presidencia.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
pressbooks.pub,"HTTPSConnectionPool(host='pressbooks.pub', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pressbooks.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
presstur.com,"HTTPSConnectionPool(host='presstur.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.presstur.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))"
priberam.org,"HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))","HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))"
pricee.vn,"HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out.","HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out. (read timeout=2)"
pricespy.co.nz,"HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pricespy.co.nz', port=443): Read timed out. (read timeout=2)"
pricesworld.net,"HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out.","HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out."
prijs-trappen.be,"HTTPSConnectionPool(host='prijs-trappen.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddd647d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='prijs-trappen.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddbc31b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prim.lt,"HTTPSConnectionPool(host='prim.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dda76da90>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.prim.lt', port=80): Read timed out. (read timeout=2)"
prima-namjestaj.hr,"HTTPSConnectionPool(host='prima-namjestaj.hr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='prima-namjestaj.hr', port=80): Read timed out. (read timeout=2)"
primabazar.cz,"HTTPSConnectionPool(host='primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.primabazar.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
prnewswire.com,"HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='prnewswire.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
procuraduria.gov.co,"HTTPSConnectionPool(host='procuraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddbf96130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='procuraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dd9e61ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prof.lv,"HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)"
promenad.hu,"HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)"
promenadanovisad.rs,"HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='promenadanovisad.rs', port=80): Read timed out. (read timeout=2)"
promerica.fi.cr,"HTTPSConnectionPool(host='promerica.fi.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dd72a8820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='promerica.fi.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddb993d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promodirecta.com.ar,"HTTPSConnectionPool(host='promodirecta.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='promodirecta.com.ar', port=80): Read timed out. (read timeout=2)"
propisi.com,"HTTPSConnectionPool(host='propisi.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='propisi.com', port=80): Read timed out. (read timeout=2)"
proprint.ro,"HTTPConnectionPool(host='www.proprint.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.proprint.ro', port=80): Read timed out. (read timeout=2)"
proshareng.com,"HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)"
protexin.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
protoporia.gr,"HTTPSConnectionPool(host='protoporia.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'protoporia.gr' doesn't match 'www.protoporia.gr'"")))",Exceeded 30 redirects.
provincia.tn.it,"HTTPSConnectionPool(host='provincia.tn.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddbd75dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provincia.tn.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddfc75190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
provisible.nl,"HTTPSConnectionPool(host='provisible.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dddf86b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provisible.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dd5221490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prtfl.co.il,"HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.prtfl.co.il', port=443): Read timed out. (read timeout=2)"
psau.edu.sa,"HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='psau.edu.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
psd.gov.jo,"HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
psiquiatria.com,"HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)"
pta.gov.pk,"HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ptt.gov.tr,"HTTPSConnectionPool(host='ptt.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1ddc9f4a00>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ptt.gov.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1ddd812970>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))"
pub.ro,"HTTPSConnectionPool(host='pub.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dde1df790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pub.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddbc31a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
public-welfare.com,"HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)"
publinews.gt,"HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.publinews.gt', port=443): Read timed out. (read timeout=2)"
publishing.service.gov.uk,"HTTPSConnectionPool(host='publishing.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dd5c36dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='publishing.service.gov.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dddfb26d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puc-rio.br,"HTTPSConnectionPool(host='puc-rio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddbd5e550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puc-rio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddad8bd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puce.edu.ec,"HTTPSConnectionPool(host='puce.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddf57a490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puce.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dd5c9f6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pucgoias.edu.br,"HTTPSConnectionPool(host='pucgoias.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1ddde643a0>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pucgoias.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1dde252490>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))"
pucminas.br,"HTTPSConnectionPool(host='pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.pucminas.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pulzo.com,"HTTPSConnectionPool(host='pulzo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1dd650e7f0>, 'Connection to pulzo.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pulzo.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1ddc74e400>, 'Connection to pulzo.com timed out. (connect timeout=2)'))"
punjab.gov.pk,"HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddd6793a0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='punjab.gov.pk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1dde538130>, 'Connection to punjab.gov.pk timed out. (connect timeout=2)'))"
pupulandia.fi,"HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)"
putereaplantelor.ro,"HTTPSConnectionPool(host='www.putereaplantelor.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.putereaplantelor.ro', port=443): Read timed out. (read timeout=2)"
pwr.edu.pl,"HTTPSConnectionPool(host='pwr.edu.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pwr.edu.pl', port=443): Read timed out. (read timeout=2)"
pycca.com,"HTTPSConnectionPool(host='pycca.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ddd8e8520>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pycca.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddebcff10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pylimas.lt,"HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
qatips.net,"HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)"
quedigital.com.ar,"HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)"
quito.gob.ec,"HTTPSConnectionPool(host='quito.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quito.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1ddd459490>, 'Connection to quito.gob.ec timed out. (connect timeout=2)'))"
quitoinforma.gob.ec,"HTTPSConnectionPool(host='quitoinforma.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.quitoinforma.gob.ec', port=80): Read timed out. (read timeout=2)"
raanana.muni.il,"HTTPSConnectionPool(host='raanana.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1dddc9d8e0>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='raanana.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1dddde0490>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))"
rabota.ru,"HTTPSConnectionPool(host='rabota.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1dd8d95490>, 'Connection to rabota.ru timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rabota.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1dd752aeb0>, 'Connection to rabota.ru timed out. (connect timeout=2)'))"
radio1.lv,"HTTPSConnectionPool(host='radio1.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radio1.lv', port=443): Read timed out. (read timeout=2)"
radiokim.net,"HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)"
radiomontecarlo.com.uy,"HTTPSConnectionPool(host='radiomontecarlo.com.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1dd9563580>, 'Connection to radiomontecarlo.com.uy timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomontecarlo.com.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1dde161c70>, 'Connection to radiomontecarlo.com.uy timed out. (connect timeout=2)'))"
radiomundial.com.ve,"HTTPSConnectionPool(host='radiomundial.com.ve', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1dd8d95700>, 'Connection to radiomundial.com.ve timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomundial.com.ve', port=80): Read timed out. (read timeout=2)"
radiopopular.pt,"HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))","HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))"
radioromaniacultural.ro,"HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out.","HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out."
radiosago.cl,"HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)"
radiosantafe.com,"HTTPSConnectionPool(host='radiosantafe.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiosantafe.com' doesn't match 'www.radiosantafe.com'"")))","HTTPConnectionPool(host='radiosantafe.com', port=80): Read timed out. (read timeout=2)"
raiceshandcrafts.com,"HTTPConnectionPool(host='www.stuartvener.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.stuartvener.com', port=80): Read timed out. (read timeout=2)"
raiffeisen.ro,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))"
rakuten.co.jp,"HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)"
rakuten.com.tw,"HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)"
rakuten.ne.jp,"HTTPSConnectionPool(host='rakuten.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dd5de84f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rakuten.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ddd948a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ramajudicial.gov.co,"HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rayhon.me,"HTTPSConnectionPool(host='rayhon.me', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='rayhon.me', port=443): Read timed out. (read timeout=2)"
rbi.org.in,"HTTPSConnectionPool(host='rbi.org.in', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='rbi.org.in', port=443): Read timed out. (read timeout=2)"
rchsd.org,"HTTPSConnectionPool(host='rchsd.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dd6094070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rchsd.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1dd62a7c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rdpad.lv,"HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rdvmedicaux.com,"HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))","HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))"
