stou.ac.th,"HTTPSConnectionPool(host='stou.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0daf3d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='stou.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0e458fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
stradini.lv,"HTTPSConnectionPool(host='stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
straitstimes.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
strathmore.edu,"HTTPSConnectionPool(host='strathmore.edu', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='strathmore.edu', port=80): Read timed out. (read timeout=2)"
struktuurifondid.ee,"HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
struma.bg,"HTTPSConnectionPool(host='struma.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='struma.bg', port=443): Read timed out. (read timeout=2)"
studentlanka.com,"HTTPSConnectionPool(host='studentlanka.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='studentlanka.com', port=80): Read timed out. (read timeout=2)"
studentski.hr,"HTTPSConnectionPool(host='studentski.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='studentski.hr', port=443): Read timed out. (read timeout=2)"
studio-aix.com,"HTTPSConnectionPool(host='studio-aix.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0b1d4910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='studio-aix.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0c40f5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
studysite.org,"HTTPSConnectionPool(host='studysite.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='studysite.org', port=80): Read timed out. (read timeout=2)"
stylesatlife.com,"HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)"
suaramerdeka.com,"HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)"
submarino.com.br,"HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)"
sud.rs,"HTTPSConnectionPool(host='sud.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0dad0a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sud.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0a648e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sudrf.ru,"HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sukasa.com,"HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)"
sukl.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
sukl.sk,"HTTPSConnectionPool(host='www.sukl.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sukl.sk', port=443): Read timed out. (read timeout=2)"
sun.ac.za,"HTTPSConnectionPool(host='sun.ac.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb08f79160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sun.ac.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb090ff5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
superdrug.com,"HTTPSConnectionPool(host='superdrug.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='superdrug.com', port=80): Read timed out. (read timeout=2)"
superintendencia.gob.ni,"HTTPSConnectionPool(host='superintendencia.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0c9c40d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='superintendencia.gob.ni', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb0852feb0>, 'Connection to superintendencia.gob.ni timed out. (connect timeout=2)'))"
supermag.bg,"HTTPSConnectionPool(host='supermag.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.supermag.bg', port=443): Read timed out. (read timeout=2)"
superpages.com,"HTTPSConnectionPool(host='superpages.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb0b75d4c0>, 'Connection to superpages.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='superpages.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb0e736460>, 'Connection to superpages.com timed out. (connect timeout=2)'))"
suruga-ya.jp,"HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))","HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))"
sut.ac.th,"HTTPSConnectionPool(host='sut.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb061d37c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sut.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb079e6340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
svejo.net,"HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)"
svepomoci.cz,"HTTPSConnectionPool(host='svepomoci.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='svepomoci.cz', port=443): Read timed out. (read timeout=2)"
svu.edu.eg,"HTTPSConnectionPool(host='svu.edu.eg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb04d9a520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='svu.edu.eg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb084a3df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
svutennis.nl,"HTTPSConnectionPool(host='svutennis.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0cd36b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='svutennis.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb07321370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sweclockers.com,"HTTPSConnectionPool(host='www.sweclockers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb058641c0>, 'Connection to www.sweclockers.com timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.sweclockers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb05afa580>, 'Connection to www.sweclockers.com timed out. (connect timeout=2)'))"
swiat-zdrowia.pl,"HTTPSConnectionPool(host='swiat-zdrowia.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'swiat-zdrowia.pl' doesn't match either of '*.neuca.pl', 'neuca.pl'"")))","HTTPSConnectionPool(host='www.swiat-zdrowia.pl', port=443): Read timed out. (read timeout=2)"
swissinfo.ch,"HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
swu.bg,"HTTPSConnectionPool(host='swu.bg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb09e532e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='swu.bg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0ca56280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
szu.sk,"HTTPSConnectionPool(host='szu.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0cb16a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='szu.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb04a40f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
t24.tn,"HTTPSConnectionPool(host='t24.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb04d8f6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='t24.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0d039130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
t3.com,"HTTPSConnectionPool(host='t3.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb0faac4f0>, 'Connection to t3.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='t3.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb05864430>, 'Connection to t3.com timed out. (connect timeout=2)'))"
taalwerkplaatsdrenthe.nl,"HTTPSConnectionPool(host='taalwerkplaatsdrenthe.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0be0aa00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='taalwerkplaatsdrenthe.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0d766a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tabirai.net,"HTTPSConnectionPool(host='tabirai.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb049a4730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tabirai.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb08a37520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tablondeanuncios.com,Exceeded 30 redirects.,Exceeded 30 redirects.
tallinnlv.ee,"HTTPSConnectionPool(host='tallinnlv.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb0b2a2250>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tallinnlv.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb037bfb50>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))"
taloustaito.fi,"HTTPSConnectionPool(host='taloustaito.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'taloustaito.fi' doesn't match either of 'www.veronmaksajat.fi', 'veronmaksajat.fi', 'www.taloustaito.fi', 'www.taxfax.fi'"")))","HTTPSConnectionPool(host='www.taloustaito.fi', port=443): Read timed out. (read timeout=2)"
tamano.ma,"HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
tamm.abudhabi,"HTTPSConnectionPool(host='www.tamm.abudhabi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tamm.abudhabi', port=80): Read timed out. (read timeout=2)"
tanea.gr,"HTTPSConnectionPool(host='www.tanea.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.tanea.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
tcd.ie,"HTTPSConnectionPool(host='tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
teachfornigeria.org,"HTTPSConnectionPool(host='teachfornigeria.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='teachfornigeria.org', port=80): Read timed out. (read timeout=2)"
techcare.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
techcombank.com.vn,"HTTPSConnectionPool(host='techcombank.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='techcombank.com.vn', port=443): Read timed out. (read timeout=2)"
techmoran.com,"HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)"
techno-science.net,"HTTPSConnectionPool(host='techno-science.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'techno-science.net' doesn't match 'www.techno-science.net'"")))","HTTPSConnectionPool(host='www.techno-science.net', port=443): Read timed out. (read timeout=2)"
technologytimes.pk,"HTTPSConnectionPool(host='technologytimes.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.technologytimes.pk', port=443): Read timed out. (read timeout=2)"
technopro-online.com,"HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)"
techradar.com,"HTTPSConnectionPool(host='techradar.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb08c155b0>, 'Connection to techradar.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='techradar.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb049695e0>, 'Connection to techradar.com timed out. (connect timeout=2)'))"
techtunes.co,"HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)"
tecnacional.edu.ni,"HTTPSConnectionPool(host='tecnacional.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb09448520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tecnacional.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0dad0cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tee.gr,"HTTPSConnectionPool(host='tee.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0496d220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tee.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb038001c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teeitse.com,"HTTPSConnectionPool(host='teeitse.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='teeitse.com', port=443): Read timed out. (read timeout=2)"
teiath.gr,"HTTPSConnectionPool(host='teiath.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0254b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teiath.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0c8181c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiemt.gr,"HTTPSConnectionPool(host='teiemt.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0b53d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teiemt.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb067fa1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiep.gr,"HTTPSConnectionPool(host='teiep.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb08363ac0>, 'Connection to teiep.gr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='teiep.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb0d5f76d0>, 'Connection to teiep.gr timed out. (connect timeout=2)'))"
teimes.gr,"HTTPSConnectionPool(host='teimes.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0bb01cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='teimes.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb046ba310>, 'Connection to teimes.gr timed out. (connect timeout=2)'))"
teismai.lt,"HTTPSConnectionPool(host='teismai.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0c3e0f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teismai.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb08fe38e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teithe.gr,"HTTPSConnectionPool(host='teithe.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0bf5dfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teithe.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb08a37ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiwest.gr,"HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))"
telanganatoday.com,"HTTPSConnectionPool(host='telanganatoday.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='telanganatoday.com', port=443): Read timed out. (read timeout=2)"
telcel.com,"HTTPSConnectionPool(host='telcel.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb0a22fe20>, 'Connection to telcel.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='telcel.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcb067fa070>, 'Connection to telcel.com timed out. (connect timeout=2)'))"
telecomunicaciones.gob.ec,"HTTPSConnectionPool(host='telecomunicaciones.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'telecomunicaciones.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
telefonai.eu,"HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)"
telefono-societa.it,"HTTPSConnectionPool(host='telefono-societa.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb0cc55820>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.telefono-societa.it', port=80): Read timed out. (read timeout=2)"
telhai.ac.il,"HTTPSConnectionPool(host='telhai.ac.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcb08fe3370>, 'Connection to telhai.ac.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='telhai.ac.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb0c9f2340>: Failed to establish a new connection: [Errno 113] No route to host'))"
