storylog.co,"HTTPSConnectionPool(host='storylog.co', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='storylog.co', port=443): Read timed out. (read timeout=2)"
stou.ac.th,"HTTPSConnectionPool(host='stou.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c53b3610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='stou.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c5aa60a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
stradini.lv,"HTTPSConnectionPool(host='stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.stradini.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
straitstimes.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
strathmore.edu,"HTTPSConnectionPool(host='strathmore.edu', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='strathmore.edu', port=80): Read timed out. (read timeout=2)"
structum.lt,"HTTPSConnectionPool(host='structum.lt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53c46b85b0>, 'Connection to structum.lt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='structum.lt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53c4cd34f0>, 'Connection to structum.lt timed out. (connect timeout=2)'))"
struktuurifondid.ee,"HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='struktuurifondid.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
studentlanka.com,"HTTPSConnectionPool(host='studentlanka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='studentlanka.com', port=443): Read timed out. (read timeout=2)"
studio-aix.com,"HTTPSConnectionPool(host='studio-aix.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c28e3fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='studio-aix.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c4391be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
studium.at,"HTTPSConnectionPool(host='www.studium.at', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.studium.at', port=443): Read timed out. (read timeout=2)"
studyrankersonline.com,"HTTPSConnectionPool(host='studyrankersonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'studyrankersonline.com' doesn't match 'www.studyrankersonline.com'"")))","HTTPSConnectionPool(host='studyrankersonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'studyrankersonline.com' doesn't match 'www.studyrankersonline.com'"")))"
stylesatlife.com,"HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='stylesatlife.com', port=443): Read timed out. (read timeout=2)"
suaramerdeka.com,"HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='suaramerdeka.com', port=443): Read timed out. (read timeout=2)"
submarino.com.br,"HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.submarino.com.br', port=443): Read timed out. (read timeout=2)"
sud.rs,"HTTPSConnectionPool(host='sud.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c30c6910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sud.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c1ac1310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sudrf.ru,"HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sukasa.com,"HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sukasa.com', port=443): Read timed out. (read timeout=2)"
sukl.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
sun.ac.za,"HTTPSConnectionPool(host='sun.ac.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c0481b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sun.ac.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c0ba58b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
suomenluonto.fi,"HTTPSConnectionPool(host='suomenluonto.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='suomenluonto.fi', port=443): Read timed out. (read timeout=2)"
superdrug.com,"HTTPSConnectionPool(host='superdrug.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='superdrug.com', port=80): Read timed out. (read timeout=2)"
superintendencia.gob.ni,"HTTPSConnectionPool(host='superintendencia.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53befc32e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='superintendencia.gob.ni', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53bff31ee0>, 'Connection to superintendencia.gob.ni timed out. (connect timeout=2)'))"
superpages.com,"HTTPSConnectionPool(host='superpages.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53c2e86970>, 'Connection to superpages.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='superpages.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53bfb23730>, 'Connection to superpages.com timed out. (connect timeout=2)'))"
suruga-ya.jp,"HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))","HTTPSConnectionPool(host='suruga-ya.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'suruga-ya.jp' doesn't match 'www.suruga-ya.jp'"")))"
sut.ac.th,"HTTPSConnectionPool(host='sut.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c3788580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sut.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c4494eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
svejo.net,"HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='svejo.net', port=443): Read timed out. (read timeout=2)"
svu.edu.eg,"HTTPSConnectionPool(host='svu.edu.eg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c0990460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='svu.edu.eg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53bd7116d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
svutennis.nl,"HTTPSConnectionPool(host='svutennis.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c09902b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='svutennis.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53bd4d4880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sweclockers.com,"HTTPSConnectionPool(host='www.sweclockers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53bdf626a0>, 'Connection to www.sweclockers.com timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.sweclockers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53c550aa30>, 'Connection to www.sweclockers.com timed out. (connect timeout=2)'))"
swiat-zdrowia.pl,"HTTPSConnectionPool(host='swiat-zdrowia.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'swiat-zdrowia.pl' doesn't match either of '*.neuca.pl', 'neuca.pl'"")))","HTTPSConnectionPool(host='www.swiat-zdrowia.pl', port=443): Read timed out. (read timeout=2)"
swissinfo.ch,"HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='swissinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
swu.bg,"HTTPSConnectionPool(host='swu.bg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53bc12a820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='swu.bg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c1825dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
szu.sk,"HTTPSConnectionPool(host='szu.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c3eec430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='szu.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c4502b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
t24.tn,"HTTPSConnectionPool(host='t24.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c3788d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='t24.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53bfb31340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
taalwerkplaatsdrenthe.nl,"HTTPSConnectionPool(host='taalwerkplaatsdrenthe.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c2477520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='taalwerkplaatsdrenthe.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c44e4280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tabirai.net,"HTTPSConnectionPool(host='tabirai.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c41a9070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tabirai.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c3c571c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tablondeanuncios.com,Exceeded 30 redirects.,Exceeded 30 redirects.
tainhac365.org,"HTTPSConnectionPool(host='tainhac365.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tainhac365.org', port=443): Read timed out."
tainhacmienphi.biz,"HTTPSConnectionPool(host='tainhacmienphi.biz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tainhacmienphi.biz', port=443): Read timed out. (read timeout=2)"
tainhacmoi.biz,"HTTPSConnectionPool(host='tainhacmoi.biz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tainhacmoi.biz', port=443): Read timed out. (read timeout=2)"
takashimaya.co.jp,"HTTPSConnectionPool(host='www.takashimaya.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.takashimaya.co.jp', port=443): Read timed out. (read timeout=2)"
talentoincluir.com.br,"HTTPSConnectionPool(host='talentoincluir.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='talentoincluir.com.br', port=443): Read timed out. (read timeout=2)"
tallinnlv.ee,"HTTPSConnectionPool(host='tallinnlv.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53c34b5df0>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tallinnlv.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53bafe59a0>, 'Connection to tallinnlv.ee timed out. (connect timeout=2)'))"
taloustaito.fi,"HTTPSConnectionPool(host='taloustaito.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'taloustaito.fi' doesn't match either of 'www.veronmaksajat.fi', 'veronmaksajat.fi', 'www.taloustaito.fi', 'www.taxfax.fi'"")))","HTTPSConnectionPool(host='www.taloustaito.fi', port=443): Read timed out. (read timeout=2)"
tamano.ma,"HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='tamano.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
tamm.abudhabi,"HTTPSConnectionPool(host='www.tamm.abudhabi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tamm.abudhabi', port=80): Read timed out. (read timeout=2)"
tapchicongsan.org.vn,"HTTPSConnectionPool(host='tapchicongsan.org.vn', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tapchicongsan.org.vn', port=80): Read timed out. (read timeout=2)"
tarimorman.gov.tr,"HTTPSConnectionPool(host='www.tarimorman.gov.tr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tarimorman.gov.tr', port=443): Read timed out. (read timeout=2)"
tcd.ie,"HTTPSConnectionPool(host='tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.tcd.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
tdgtest.it,"HTTPSConnectionPool(host='tdgtest.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tdgtest.it', port=80): Read timed out. (read timeout=2)"
teachfornigeria.org,"HTTPSConnectionPool(host='teachfornigeria.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='teachfornigeria.org', port=80): Read timed out. (read timeout=2)"
techcare.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
techcombank.com.vn,"HTTPSConnectionPool(host='techcombank.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='techcombank.com.vn', port=443): Read timed out. (read timeout=2)"
techmoran.com,"HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='techmoran.com', port=443): Read timed out. (read timeout=2)"
technopro-online.com,"HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.technopro-online.com', port=443): Read timed out. (read timeout=2)"
technorama.lt,"HTTPSConnectionPool(host='www.technorama.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.technorama.lt', port=443): Read timed out. (read timeout=2)"
techtunes.co,"HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.techtunes.io', port=443): Read timed out. (read timeout=2)"
tecnacional.edu.ni,"HTTPSConnectionPool(host='tecnacional.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c52e2670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tecnacional.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c299c2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tecoloco.com.ni,"HTTPSConnectionPool(host='tecoloco.com.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c3e95550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tecoloco.com.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53bc15ea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tee.gr,"HTTPSConnectionPool(host='tee.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c40a0520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tee.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c439fbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiath.gr,"HTTPSConnectionPool(host='teiath.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c4e44b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teiath.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c4088070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiemt.gr,"HTTPSConnectionPool(host='teiemt.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53bd1b6130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teiemt.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53bd9727f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiep.gr,"HTTPSConnectionPool(host='teiep.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53bd731e20>, 'Connection to teiep.gr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='teiep.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53c4454be0>, 'Connection to teiep.gr timed out. (connect timeout=2)'))"
teimes.gr,"HTTPSConnectionPool(host='teimes.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c2d3a1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='teimes.gr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53c3f23a30>, 'Connection to teimes.gr timed out. (connect timeout=2)'))"
teismai.lt,"HTTPSConnectionPool(host='teismai.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53bdff31c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teismai.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c41f30a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teithe.gr,"HTTPSConnectionPool(host='teithe.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c317a970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='teithe.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c2280550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
teiwest.gr,"HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='teiwest.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))"
telcel.com,"HTTPSConnectionPool(host='telcel.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53bc0a1100>, 'Connection to telcel.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='telcel.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f53c2c7c130>, 'Connection to telcel.com timed out. (connect timeout=2)'))"
telecomunicaciones.gob.ec,"HTTPSConnectionPool(host='telecomunicaciones.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'telecomunicaciones.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
telefonai.eu,"HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='telefonai.eu', port=443): Read timed out. (read timeout=2)"
telefono-societa.it,"HTTPSConnectionPool(host='telefono-societa.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53c363dbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.telefono-societa.it', port=80): Read timed out. (read timeout=2)"
telepolis.pl,"HTTPSConnectionPool(host='www.telepolis.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.telepolis.pl', port=443): Read timed out. (read timeout=2)"
telhai.ac.il,"HTTPSConnectionPool(host='telhai.ac.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53ba8a1bb0>, 'Connection to telhai.ac.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='telhai.ac.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53c4a9f700>: Failed to establish a new connection: [Errno 113] No route to host'))"
