ulaval.ca,"HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
uludag.edu.tr,"HTTPSConnectionPool(host='uludag.edu.tr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='uludag.edu.tr', port=80): Read timed out. (read timeout=2)"
ulusiada.pt,"HTTPSConnectionPool(host='ulusiada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537543a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ulusiada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb538fefc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
um5.ac.ma,"HTTPSConnectionPool(host='um5.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536e37dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='um5.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5385352b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uma.es,"HTTPSConnectionPool(host='uma.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536ca8e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uma.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5383509a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umanitoba.ca,"HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
umfcd.ro,"HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)"
umich.mx,"HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uminho.pt,"HTTPSConnectionPool(host='uminho.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535c1c6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uminho.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5367cc280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umm.ac.id,"HTTPSConnectionPool(host='umm.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.umm.ac.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb53638ed00>, 'Connection to www.umm.ac.id timed out. (connect timeout=2)'))"
ums.ac.id,"HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
umsa.bo,"HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unach.edu.ec,"HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unad.edu.co,"HTTPSConnectionPool(host='unad.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535c1cb20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unad.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5352acfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unan.edu.ni,"HTTPSConnectionPool(host='unan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535637ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5361bee50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uncoma.edu.ar,"HTTPSConnectionPool(host='uncoma.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5375e0d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uncoma.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53529cf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
undip.ac.id,"HTTPSConnectionPool(host='undip.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='undip.ac.id', port=80): Read timed out. (read timeout=2)"
uned.es,"HTTPSConnectionPool(host='uned.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53471f7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uned.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5352e3ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unemi.edu.ec,"HTTPSConnectionPool(host='unemi.edu.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb5372ffeb0>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unemi.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb534dbfd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unescwa.org,"HTTPSConnectionPool(host='unescwa.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5361be850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unescwa.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5347a4070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-lj.si,"HTTPSConnectionPool(host='uni-lj.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb53394afa0>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uni-lj.si', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb534309be0>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))"
uni-muenchen.de,"HTTPSConnectionPool(host='uni-muenchen.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535fb7760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-muenchen.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53429f430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-regensburg.de,"HTTPSConnectionPool(host='uni-regensburg.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5379248b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-regensburg.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb535bb2a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-sofia.bg,"HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)"
uni-vt.bg,"HTTPSConnectionPool(host='uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unibg.it,"HTTPSConnectionPool(host='unibg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5360efd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unibg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5378f3d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unicamp.br,"HTTPSConnectionPool(host='unicamp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb533a94f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unicamp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb533f16e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unican.es,"HTTPSConnectionPool(host='unican.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb532d7bca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unican.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb534311ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unidivers.fr,"HTTPSConnectionPool(host='www.unidivers.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unidivers.fr', port=443): Read timed out. (read timeout=2)"
unifap.br,"HTTPSConnectionPool(host='unifap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536b687f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='unifap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5378f3ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
uniindia.com,"HTTPSConnectionPool(host='uniindia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.uniindia.com', port=80): Read timed out. (read timeout=2)"
unimal.ac.id,"HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)"
unimet.edu.ve,"HTTPSConnectionPool(host='unimet.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53813f070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimet.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb537d7a1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimib.it,"HTTPSConnectionPool(host='unimib.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535b54ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimib.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53382a5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimilitar.edu.co,"HTTPSConnectionPool(host='unimilitar.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb532c82370>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unimilitar.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb533f21fa0>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))"
uniminuto.edu,"HTTPSConnectionPool(host='uniminuto.edu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb5320477c0>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uniminuto.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb536c52bb0>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))"
unin.hr,"HTTPSConnectionPool(host='unin.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unin.hr', port=443): Read timed out. (read timeout=2)"
unina.it,"HTTPSConnectionPool(host='unina.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537debf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unina.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5337dbe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unios.hr,"HTTPSConnectionPool(host='unios.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb531d1b280>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unios.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5371f42e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipamplona.edu.co,"HTTPSConnectionPool(host='unipamplona.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536115b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipamplona.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5364b60d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipiloto.edu.co,"HTTPSConnectionPool(host='unipiloto.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb531d5daf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipiloto.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5381500a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniqlo.com,"HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)"
unirio.br,"HTTPSConnectionPool(host='unirio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53580b850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb531f74b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unirioja.es,"HTTPSConnectionPool(host='unirioja.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5373d8a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirioja.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5382d0c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma2.it,"HTTPSConnectionPool(host='uniroma2.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb531f74e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uniroma2.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb531fd5070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma3.it,"HTTPSConnectionPool(host='uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unisa.ac.za,"HTTPSConnectionPool(host='unisa.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unisa.ac.za', port=443): Max retries exceeded with url: /sites/corporate/default (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
unisant.edu.mx,"HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)"
unisba.ac.id,"HTTPSConnectionPool(host='unisba.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb538564100>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unisba.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb537b31ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unisimon.edu.co,"HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unisul.br,"HTTPSConnectionPool(host='unisul.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unisul.br', port=443): Read timed out. (read timeout=2)"
unito.it,"HTTPSConnectionPool(host='unito.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb530f1adf0>, 'Connection to unito.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unito.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb5311b2040>, 'Connection to unito.it timed out. (connect timeout=2)'))"
unium.cz,"HTTPSConnectionPool(host='unium.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.unium.cz', port=80): Read timed out. (read timeout=2)"
univ-msila.dz,"HTTPSConnectionPool(host='univ-msila.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb530f0ffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='univ-msila.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb531f3bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
univ-setif2.dz,"HTTPSConnectionPool(host='univ-setif2.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537756040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univ-setif2.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53192c100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univ-tlemcen.dz,"HTTPSConnectionPool(host='univ-tlemcen.dz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.univ-tlemcen.dz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
univalle.edu.co,"HTTPSConnectionPool(host='univalle.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53764faf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univalle.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53120c430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univap.br,"HTTPSConnectionPool(host='univap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb538083190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb537704130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
universiteitleiden.nl,"HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)"
univr.it,"HTTPSConnectionPool(host='univr.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb53608ed90>, 'Connection to univr.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='univr.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb530abfca0>, 'Connection to univr.it timed out. (connect timeout=2)'))"
unizd.hr,"HTTPSConnectionPool(host='unizd.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5366e2880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unizd.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52fd15070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unj.ac.id,"HTTPSConnectionPool(host='unj.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='unj.ac.id', port=80): Read timed out. (read timeout=2)"
unl.edu.ec,"HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unl.pt,"HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unlimitedallstars.com,"HTTPConnectionPool(host='www.unlimitedallstars.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unlimitedallstars.com', port=80): Read timed out. (read timeout=2)"
unlpam.edu.ar,"HTTPSConnectionPool(host='unlpam.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb532b78eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unlpam.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb531939880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unmuhjember.ac.id,"HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unne.edu.ar,"HTTPSConnectionPool(host='unne.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb538e87670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unne.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52fe94370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unodc.org,"HTTPSConnectionPool(host='unodc.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5309ef4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unodc.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52fe3d430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unotices.com,"HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)"
unp.ac.id,"HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unpatti.ac.id,"HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)"
unpret.ro,"HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)"
uns.ac.rs,"HTTPSConnectionPool(host='uns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536de6a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5319f1c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unse.edu.ar,"HTTPSConnectionPool(host='unse.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5379c5f40>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unse.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53843bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unsrat.ac.id,"HTTPSConnectionPool(host='unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
untirta.ac.id,"HTTPSConnectionPool(host='untirta.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='untirta.ac.id', port=443): Read timed out. (read timeout=2)"
uob.edu.bh,"HTTPSConnectionPool(host='uob.edu.bh', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537bc1040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uob.edu.bh', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53625e520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uop.gr,"HTTPSConnectionPool(host='uop.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53925d1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uop.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb530a6f130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
up.ac.za,"HTTPSConnectionPool(host='up.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb538d1c5b0>, 'Connection to up.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='up.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb531fe0250>, 'Connection to up.ac.za timed out. (connect timeout=2)'))"
upatras.gr,"HTTPSConnectionPool(host='upatras.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb533ae7f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upatras.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53417c550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
upb.ro,"HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)"
upcitemdb.com,"HTTPSConnectionPool(host='upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uph.edu,"HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)"
upv.es,"HTTPSConnectionPool(host='upv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536a6f070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb535ad7970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uq.edu.au,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
uraccan.edu.ni,"HTTPSConnectionPool(host='uraccan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5372e6670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uraccan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52f7479a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
urdu2eng.com,"HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)"
urduinc.com,"HTTPSConnectionPool(host='www.urduinc.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.urduinc.com', port=443): Read timed out. (read timeout=2)"
uruguayconcursa.gub.uy,"HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: // (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
us.es,"HTTPSConnectionPool(host='us.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537137eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='us.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb533dc5d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usdwellhouse.com,"HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)"
usfx.bo,"HTTPSConnectionPool(host='usfx.bo', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usfx.bo', port=80): Read timed out. (read timeout=2)"
uskudar.edu.tr,"HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
usm.my,"HTTPSConnectionPool(host='usm.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb5372ef8b0>, 'Connection to usm.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='usm.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb52fea2940>, 'Connection to usm.my timed out. (connect timeout=2)'))"
usmba.ac.ma,"HTTPSConnectionPool(host='usmba.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53782b070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usmba.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb533c1fe50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usnews.com,"HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usnews.com', port=80): Read timed out. (read timeout=2)"
uson.mx,"HTTPSConnectionPool(host='uson.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb52fe3d2b0>, 'Connection to uson.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uson.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb5364b69d0>, 'Connection to uson.mx timed out. (connect timeout=2)'))"
usta.edu.co,"HTTPSConnectionPool(host='usta.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535a6b4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usta.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb536ae2c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usv.ro,"HTTPSConnectionPool(host='usv.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usv.ro', port=443): Read timed out. (read timeout=2)"
uta.edu.ec,"HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)"
utalca.cl,"HTTPSConnectionPool(host='utalca.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb52fb954f0>, 'Connection to utalca.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utalca.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb5309efcd0>, 'Connection to utalca.cl timed out. (connect timeout=2)'))"
utcluj.ro,"HTTPSConnectionPool(host='utcluj.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5352e3f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='utcluj.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53799e670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
utl.pt,"HTTPSConnectionPool(host='utl.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5382d0760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utl.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53580b280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utlib.ee,"HTTPSConnectionPool(host='utlib.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb531f5ceb0>, 'Connection to utlib.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utlib.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb537c966d0>, 'Connection to utlib.ee timed out. (connect timeout=2)'))"
utmachala.edu.ec,"HTTPSConnectionPool(host='utmachala.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb538f8ebe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utmachala.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb536212af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utulok-levice.sk,"HTTPSConnectionPool(host='utulok-levice.sk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='utulok-levice.sk', port=80): Read timed out. (read timeout=2)"
uv.es,"HTTPSConnectionPool(host='uv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb535ad74c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb536534040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uvzsr.sk,"HTTPSConnectionPool(host='uvzsr.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53382a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uvzsr.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb53427fdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uwa.edu.au,"HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)"
vaduguns.lv,"HTTPSConnectionPool(host='vaduguns.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb52f3de460>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='vaduguns.lv', port=80): Read timed out. (read timeout=2)"
vaga.lt,"HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)"
valeta.bg,"HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)"
valledelcauca.gov.co,"HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
valoda.lv,"HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
vasezdravlje.com,"HTTPSConnectionPool(host='www.vasezdravlje.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vasezdravlje.com', port=443): Read timed out. (read timeout=2)"
vatican.va,"HTTPSConnectionPool(host='vatican.va', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb52fe3d400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52f44aaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdi.lt,"HTTPSConnectionPool(host='vdi.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb536e8b370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vdi.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb538d86250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdu.lt,"HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)"
ve.lt,"HTTPSConnectionPool(host='ve.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ve.lt', port=443): Read timed out. (read timeout=2)"
vec.go.th,"HTTPSConnectionPool(host='vec.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5368a2bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vec.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52f2b1f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veidas.lt,"HTTPSConnectionPool(host='veidas.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb537d30d30>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.veidas.lt', port=80): Read timed out. (read timeout=2)"
veleposlanistvo.si,"HTTPSConnectionPool(host='veleposlanistvo.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb52fe497f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='veleposlanistvo.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb531d26ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verangola.net,"HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)"
vergelijken-chappers.be,"HTTPSConnectionPool(host='vergelijken-chappers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5365acb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vergelijken-chappers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb536982790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verizon.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
verkkokirjasto.fi,"HTTPSConnectionPool(host='verkkokirjasto.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb53705cb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='verkkokirjasto.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb52fe94790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veselebydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
veterinarylabsupply.com,"HTTPSConnectionPool(host='veterinarylabsupply.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='veterinarylabsupply.com', port=443): Read timed out. (read timeout=2)"
